// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type GroupPermissionsInitParameters struct {

	// the permissions to assign. The following permissions are available.
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// The group principal to assign the permissions.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Replace (true) or merge (false) the permissions. Default: true
	Replace *bool `json:"replace,omitempty" tf:"replace,omitempty"`

	// The id of the variable group to assign the permissions.
	VariableGroupID *string `json:"variableGroupId,omitempty" tf:"variable_group_id,omitempty"`
}

type GroupPermissionsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// the permissions to assign. The following permissions are available.
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// The group principal to assign the permissions.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Replace (true) or merge (false) the permissions. Default: true
	Replace *bool `json:"replace,omitempty" tf:"replace,omitempty"`

	// The id of the variable group to assign the permissions.
	VariableGroupID *string `json:"variableGroupId,omitempty" tf:"variable_group_id,omitempty"`
}

type GroupPermissionsParameters struct {

	// the permissions to assign. The following permissions are available.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// The group principal to assign the permissions.
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// The ID of the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Replace (true) or merge (false) the permissions. Default: true
	// +kubebuilder:validation:Optional
	Replace *bool `json:"replace,omitempty" tf:"replace,omitempty"`

	// The id of the variable group to assign the permissions.
	// +kubebuilder:validation:Optional
	VariableGroupID *string `json:"variableGroupId,omitempty" tf:"variable_group_id,omitempty"`
}

// GroupPermissionsSpec defines the desired state of GroupPermissions
type GroupPermissionsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupPermissionsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupPermissionsInitParameters `json:"initProvider,omitempty"`
}

// GroupPermissionsStatus defines the observed state of GroupPermissions.
type GroupPermissionsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupPermissionsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GroupPermissions is the Schema for the GroupPermissionss API. Manages permissions for aa Azure DevOps Variable Group
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type GroupPermissions struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissions) || (has(self.initProvider) && has(self.initProvider.permissions))",message="spec.forProvider.permissions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.principal) || (has(self.initProvider) && has(self.initProvider.principal))",message="spec.forProvider.principal is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.variableGroupId) || (has(self.initProvider) && has(self.initProvider.variableGroupId))",message="spec.forProvider.variableGroupId is a required parameter"
	Spec   GroupPermissionsSpec   `json:"spec"`
	Status GroupPermissionsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupPermissionsList contains a list of GroupPermissionss
type GroupPermissionsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GroupPermissions `json:"items"`
}

// Repository type metadata.
var (
	GroupPermissions_Kind             = "GroupPermissions"
	GroupPermissions_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupPermissions_Kind}.String()
	GroupPermissions_KindAPIVersion   = GroupPermissions_Kind + "." + CRDGroupVersion.String()
	GroupPermissions_GroupVersionKind = CRDGroupVersion.WithKind(GroupPermissions_Kind)
)

func init() {
	SchemeBuilder.Register(&GroupPermissions{}, &GroupPermissionsList{})
}
