apiVersion: repositorypolicy.azuredevops.crossplane.io/v1alpha1
kind: PolicyMaxFileSize
metadata:
  annotations:
    meta.upbound.io/example-id: repositorypolicy/v1alpha1/policymaxfilesize
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    blocking: true
    enabled: true
    maxFileSize: 1
    projectId: ${azuredevops_project.example.id}
    repositoryIds:
    - ${azuredevops_git_repository.example.id}

---

apiVersion: git.azuredevops.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: repositorypolicy/v1alpha1/policymaxfilesize
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Repository
    projectId: ${azuredevops_project.example.id}

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: repositorypolicy/v1alpha1/policymaxfilesize
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
