apiVersion: agent.azuredevops.m.crossplane.io/v1alpha1
kind: Queue
metadata:
  annotations:
    meta.upbound.io/example-id: agent/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    agentPoolId: ${data.azuredevops_agent_pool.example.id}
    projectId: ${azuredevops_project.example.id}

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: agent/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    name: Example Project

---

apiVersion: other.azuredevops.m.crossplane.io/v1alpha1
kind: Authorization
metadata:
  annotations:
    meta.upbound.io/example-id: agent/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    authorized: true
    projectId: ${azuredevops_project.example.id}
    resourceId: ${azuredevops_agent_queue.example.id}
    type: queue
