apiVersion: group.azuredevops.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: group/v1alpha1/group
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Example description
    displayName: Example group
    members:
    - ${data.azuredevops_group.example-readers.descriptor}
    - ${data.azuredevops_group.example-contributors.descriptor}
    scope: ${azuredevops_project.example.id}

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: group/v1alpha1/group
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Example Project
