//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAutoReviewers) DeepCopyInto(out *PolicyAutoReviewers) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAutoReviewers.
func (in *PolicyAutoReviewers) DeepCopy() *PolicyAutoReviewers {
	if in == nil {
		return nil
	}
	out := new(PolicyAutoReviewers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyAutoReviewers) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAutoReviewersInitParameters) DeepCopyInto(out *PolicyAutoReviewersInitParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]SettingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAutoReviewersInitParameters.
func (in *PolicyAutoReviewersInitParameters) DeepCopy() *PolicyAutoReviewersInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyAutoReviewersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAutoReviewersList) DeepCopyInto(out *PolicyAutoReviewersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyAutoReviewers, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAutoReviewersList.
func (in *PolicyAutoReviewersList) DeepCopy() *PolicyAutoReviewersList {
	if in == nil {
		return nil
	}
	out := new(PolicyAutoReviewersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyAutoReviewersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAutoReviewersObservation) DeepCopyInto(out *PolicyAutoReviewersObservation) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]SettingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAutoReviewersObservation.
func (in *PolicyAutoReviewersObservation) DeepCopy() *PolicyAutoReviewersObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyAutoReviewersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAutoReviewersParameters) DeepCopyInto(out *PolicyAutoReviewersParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]SettingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAutoReviewersParameters.
func (in *PolicyAutoReviewersParameters) DeepCopy() *PolicyAutoReviewersParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyAutoReviewersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAutoReviewersSpec) DeepCopyInto(out *PolicyAutoReviewersSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAutoReviewersSpec.
func (in *PolicyAutoReviewersSpec) DeepCopy() *PolicyAutoReviewersSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyAutoReviewersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAutoReviewersStatus) DeepCopyInto(out *PolicyAutoReviewersStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAutoReviewersStatus.
func (in *PolicyAutoReviewersStatus) DeepCopy() *PolicyAutoReviewersStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyAutoReviewersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidation) DeepCopyInto(out *PolicyBuildValidation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidation.
func (in *PolicyBuildValidation) DeepCopy() *PolicyBuildValidation {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyBuildValidation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidationInitParameters) DeepCopyInto(out *PolicyBuildValidationInitParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyBuildValidationSettingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidationInitParameters.
func (in *PolicyBuildValidationInitParameters) DeepCopy() *PolicyBuildValidationInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidationList) DeepCopyInto(out *PolicyBuildValidationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyBuildValidation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidationList.
func (in *PolicyBuildValidationList) DeepCopy() *PolicyBuildValidationList {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyBuildValidationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidationObservation) DeepCopyInto(out *PolicyBuildValidationObservation) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyBuildValidationSettingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidationObservation.
func (in *PolicyBuildValidationObservation) DeepCopy() *PolicyBuildValidationObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidationParameters) DeepCopyInto(out *PolicyBuildValidationParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyBuildValidationSettingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidationParameters.
func (in *PolicyBuildValidationParameters) DeepCopy() *PolicyBuildValidationParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidationSettingsInitParameters) DeepCopyInto(out *PolicyBuildValidationSettingsInitParameters) {
	*out = *in
	if in.BuildDefinitionID != nil {
		in, out := &in.BuildDefinitionID, &out.BuildDefinitionID
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FilenamePatterns != nil {
		in, out := &in.FilenamePatterns, &out.FilenamePatterns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ManualQueueOnly != nil {
		in, out := &in.ManualQueueOnly, &out.ManualQueueOnly
		*out = new(bool)
		**out = **in
	}
	if in.QueueOnSourceUpdateOnly != nil {
		in, out := &in.QueueOnSourceUpdateOnly, &out.QueueOnSourceUpdateOnly
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]SettingsScopeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidDuration != nil {
		in, out := &in.ValidDuration, &out.ValidDuration
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidationSettingsInitParameters.
func (in *PolicyBuildValidationSettingsInitParameters) DeepCopy() *PolicyBuildValidationSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidationSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidationSettingsObservation) DeepCopyInto(out *PolicyBuildValidationSettingsObservation) {
	*out = *in
	if in.BuildDefinitionID != nil {
		in, out := &in.BuildDefinitionID, &out.BuildDefinitionID
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FilenamePatterns != nil {
		in, out := &in.FilenamePatterns, &out.FilenamePatterns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ManualQueueOnly != nil {
		in, out := &in.ManualQueueOnly, &out.ManualQueueOnly
		*out = new(bool)
		**out = **in
	}
	if in.QueueOnSourceUpdateOnly != nil {
		in, out := &in.QueueOnSourceUpdateOnly, &out.QueueOnSourceUpdateOnly
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]SettingsScopeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidDuration != nil {
		in, out := &in.ValidDuration, &out.ValidDuration
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidationSettingsObservation.
func (in *PolicyBuildValidationSettingsObservation) DeepCopy() *PolicyBuildValidationSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidationSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidationSettingsParameters) DeepCopyInto(out *PolicyBuildValidationSettingsParameters) {
	*out = *in
	if in.BuildDefinitionID != nil {
		in, out := &in.BuildDefinitionID, &out.BuildDefinitionID
		*out = new(float64)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FilenamePatterns != nil {
		in, out := &in.FilenamePatterns, &out.FilenamePatterns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ManualQueueOnly != nil {
		in, out := &in.ManualQueueOnly, &out.ManualQueueOnly
		*out = new(bool)
		**out = **in
	}
	if in.QueueOnSourceUpdateOnly != nil {
		in, out := &in.QueueOnSourceUpdateOnly, &out.QueueOnSourceUpdateOnly
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]SettingsScopeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidDuration != nil {
		in, out := &in.ValidDuration, &out.ValidDuration
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidationSettingsParameters.
func (in *PolicyBuildValidationSettingsParameters) DeepCopy() *PolicyBuildValidationSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidationSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidationSpec) DeepCopyInto(out *PolicyBuildValidationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidationSpec.
func (in *PolicyBuildValidationSpec) DeepCopy() *PolicyBuildValidationSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBuildValidationStatus) DeepCopyInto(out *PolicyBuildValidationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBuildValidationStatus.
func (in *PolicyBuildValidationStatus) DeepCopy() *PolicyBuildValidationStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyBuildValidationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolution) DeepCopyInto(out *PolicyCommentResolution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolution.
func (in *PolicyCommentResolution) DeepCopy() *PolicyCommentResolution {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyCommentResolution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionInitParameters) DeepCopyInto(out *PolicyCommentResolutionInitParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyCommentResolutionSettingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionInitParameters.
func (in *PolicyCommentResolutionInitParameters) DeepCopy() *PolicyCommentResolutionInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionList) DeepCopyInto(out *PolicyCommentResolutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyCommentResolution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionList.
func (in *PolicyCommentResolutionList) DeepCopy() *PolicyCommentResolutionList {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyCommentResolutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionObservation) DeepCopyInto(out *PolicyCommentResolutionObservation) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyCommentResolutionSettingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionObservation.
func (in *PolicyCommentResolutionObservation) DeepCopy() *PolicyCommentResolutionObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionParameters) DeepCopyInto(out *PolicyCommentResolutionParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyCommentResolutionSettingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionParameters.
func (in *PolicyCommentResolutionParameters) DeepCopy() *PolicyCommentResolutionParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionSettingsInitParameters) DeepCopyInto(out *PolicyCommentResolutionSettingsInitParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyCommentResolutionSettingsScopeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionSettingsInitParameters.
func (in *PolicyCommentResolutionSettingsInitParameters) DeepCopy() *PolicyCommentResolutionSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionSettingsObservation) DeepCopyInto(out *PolicyCommentResolutionSettingsObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyCommentResolutionSettingsScopeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionSettingsObservation.
func (in *PolicyCommentResolutionSettingsObservation) DeepCopy() *PolicyCommentResolutionSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionSettingsParameters) DeepCopyInto(out *PolicyCommentResolutionSettingsParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyCommentResolutionSettingsScopeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionSettingsParameters.
func (in *PolicyCommentResolutionSettingsParameters) DeepCopy() *PolicyCommentResolutionSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionSettingsScopeInitParameters) DeepCopyInto(out *PolicyCommentResolutionSettingsScopeInitParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionSettingsScopeInitParameters.
func (in *PolicyCommentResolutionSettingsScopeInitParameters) DeepCopy() *PolicyCommentResolutionSettingsScopeInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionSettingsScopeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionSettingsScopeObservation) DeepCopyInto(out *PolicyCommentResolutionSettingsScopeObservation) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionSettingsScopeObservation.
func (in *PolicyCommentResolutionSettingsScopeObservation) DeepCopy() *PolicyCommentResolutionSettingsScopeObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionSettingsScopeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionSettingsScopeParameters) DeepCopyInto(out *PolicyCommentResolutionSettingsScopeParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionSettingsScopeParameters.
func (in *PolicyCommentResolutionSettingsScopeParameters) DeepCopy() *PolicyCommentResolutionSettingsScopeParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionSettingsScopeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionSpec) DeepCopyInto(out *PolicyCommentResolutionSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionSpec.
func (in *PolicyCommentResolutionSpec) DeepCopy() *PolicyCommentResolutionSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCommentResolutionStatus) DeepCopyInto(out *PolicyCommentResolutionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCommentResolutionStatus.
func (in *PolicyCommentResolutionStatus) DeepCopy() *PolicyCommentResolutionStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyCommentResolutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypes) DeepCopyInto(out *PolicyMergeTypes) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypes.
func (in *PolicyMergeTypes) DeepCopy() *PolicyMergeTypes {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyMergeTypes) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesInitParameters) DeepCopyInto(out *PolicyMergeTypesInitParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyMergeTypesSettingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesInitParameters.
func (in *PolicyMergeTypesInitParameters) DeepCopy() *PolicyMergeTypesInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesList) DeepCopyInto(out *PolicyMergeTypesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyMergeTypes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesList.
func (in *PolicyMergeTypesList) DeepCopy() *PolicyMergeTypesList {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyMergeTypesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesObservation) DeepCopyInto(out *PolicyMergeTypesObservation) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyMergeTypesSettingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesObservation.
func (in *PolicyMergeTypesObservation) DeepCopy() *PolicyMergeTypesObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesParameters) DeepCopyInto(out *PolicyMergeTypesParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyMergeTypesSettingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesParameters.
func (in *PolicyMergeTypesParameters) DeepCopy() *PolicyMergeTypesParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesSettingsInitParameters) DeepCopyInto(out *PolicyMergeTypesSettingsInitParameters) {
	*out = *in
	if in.AllowBasicNoFastForward != nil {
		in, out := &in.AllowBasicNoFastForward, &out.AllowBasicNoFastForward
		*out = new(bool)
		**out = **in
	}
	if in.AllowRebaseAndFastForward != nil {
		in, out := &in.AllowRebaseAndFastForward, &out.AllowRebaseAndFastForward
		*out = new(bool)
		**out = **in
	}
	if in.AllowRebaseWithMerge != nil {
		in, out := &in.AllowRebaseWithMerge, &out.AllowRebaseWithMerge
		*out = new(bool)
		**out = **in
	}
	if in.AllowSquash != nil {
		in, out := &in.AllowSquash, &out.AllowSquash
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyMergeTypesSettingsScopeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesSettingsInitParameters.
func (in *PolicyMergeTypesSettingsInitParameters) DeepCopy() *PolicyMergeTypesSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesSettingsObservation) DeepCopyInto(out *PolicyMergeTypesSettingsObservation) {
	*out = *in
	if in.AllowBasicNoFastForward != nil {
		in, out := &in.AllowBasicNoFastForward, &out.AllowBasicNoFastForward
		*out = new(bool)
		**out = **in
	}
	if in.AllowRebaseAndFastForward != nil {
		in, out := &in.AllowRebaseAndFastForward, &out.AllowRebaseAndFastForward
		*out = new(bool)
		**out = **in
	}
	if in.AllowRebaseWithMerge != nil {
		in, out := &in.AllowRebaseWithMerge, &out.AllowRebaseWithMerge
		*out = new(bool)
		**out = **in
	}
	if in.AllowSquash != nil {
		in, out := &in.AllowSquash, &out.AllowSquash
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyMergeTypesSettingsScopeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesSettingsObservation.
func (in *PolicyMergeTypesSettingsObservation) DeepCopy() *PolicyMergeTypesSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesSettingsParameters) DeepCopyInto(out *PolicyMergeTypesSettingsParameters) {
	*out = *in
	if in.AllowBasicNoFastForward != nil {
		in, out := &in.AllowBasicNoFastForward, &out.AllowBasicNoFastForward
		*out = new(bool)
		**out = **in
	}
	if in.AllowRebaseAndFastForward != nil {
		in, out := &in.AllowRebaseAndFastForward, &out.AllowRebaseAndFastForward
		*out = new(bool)
		**out = **in
	}
	if in.AllowRebaseWithMerge != nil {
		in, out := &in.AllowRebaseWithMerge, &out.AllowRebaseWithMerge
		*out = new(bool)
		**out = **in
	}
	if in.AllowSquash != nil {
		in, out := &in.AllowSquash, &out.AllowSquash
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyMergeTypesSettingsScopeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesSettingsParameters.
func (in *PolicyMergeTypesSettingsParameters) DeepCopy() *PolicyMergeTypesSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesSettingsScopeInitParameters) DeepCopyInto(out *PolicyMergeTypesSettingsScopeInitParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesSettingsScopeInitParameters.
func (in *PolicyMergeTypesSettingsScopeInitParameters) DeepCopy() *PolicyMergeTypesSettingsScopeInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesSettingsScopeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesSettingsScopeObservation) DeepCopyInto(out *PolicyMergeTypesSettingsScopeObservation) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesSettingsScopeObservation.
func (in *PolicyMergeTypesSettingsScopeObservation) DeepCopy() *PolicyMergeTypesSettingsScopeObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesSettingsScopeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesSettingsScopeParameters) DeepCopyInto(out *PolicyMergeTypesSettingsScopeParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesSettingsScopeParameters.
func (in *PolicyMergeTypesSettingsScopeParameters) DeepCopy() *PolicyMergeTypesSettingsScopeParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesSettingsScopeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesSpec) DeepCopyInto(out *PolicyMergeTypesSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesSpec.
func (in *PolicyMergeTypesSpec) DeepCopy() *PolicyMergeTypesSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMergeTypesStatus) DeepCopyInto(out *PolicyMergeTypesStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMergeTypesStatus.
func (in *PolicyMergeTypesStatus) DeepCopy() *PolicyMergeTypesStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyMergeTypesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewers) DeepCopyInto(out *PolicyMinReviewers) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewers.
func (in *PolicyMinReviewers) DeepCopy() *PolicyMinReviewers {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyMinReviewers) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersInitParameters) DeepCopyInto(out *PolicyMinReviewersInitParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyMinReviewersSettingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersInitParameters.
func (in *PolicyMinReviewersInitParameters) DeepCopy() *PolicyMinReviewersInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersList) DeepCopyInto(out *PolicyMinReviewersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyMinReviewers, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersList.
func (in *PolicyMinReviewersList) DeepCopy() *PolicyMinReviewersList {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyMinReviewersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersObservation) DeepCopyInto(out *PolicyMinReviewersObservation) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyMinReviewersSettingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersObservation.
func (in *PolicyMinReviewersObservation) DeepCopy() *PolicyMinReviewersObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersParameters) DeepCopyInto(out *PolicyMinReviewersParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyMinReviewersSettingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersParameters.
func (in *PolicyMinReviewersParameters) DeepCopy() *PolicyMinReviewersParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersSettingsInitParameters) DeepCopyInto(out *PolicyMinReviewersSettingsInitParameters) {
	*out = *in
	if in.AllowCompletionWithRejectsOrWaits != nil {
		in, out := &in.AllowCompletionWithRejectsOrWaits, &out.AllowCompletionWithRejectsOrWaits
		*out = new(bool)
		**out = **in
	}
	if in.LastPusherCannotApprove != nil {
		in, out := &in.LastPusherCannotApprove, &out.LastPusherCannotApprove
		*out = new(bool)
		**out = **in
	}
	if in.OnLastIterationRequireVote != nil {
		in, out := &in.OnLastIterationRequireVote, &out.OnLastIterationRequireVote
		*out = new(bool)
		**out = **in
	}
	if in.OnPushResetAllVotes != nil {
		in, out := &in.OnPushResetAllVotes, &out.OnPushResetAllVotes
		*out = new(bool)
		**out = **in
	}
	if in.OnPushResetApprovedVotes != nil {
		in, out := &in.OnPushResetApprovedVotes, &out.OnPushResetApprovedVotes
		*out = new(bool)
		**out = **in
	}
	if in.ReviewerCount != nil {
		in, out := &in.ReviewerCount, &out.ReviewerCount
		*out = new(float64)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyMinReviewersSettingsScopeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubmitterCanVote != nil {
		in, out := &in.SubmitterCanVote, &out.SubmitterCanVote
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersSettingsInitParameters.
func (in *PolicyMinReviewersSettingsInitParameters) DeepCopy() *PolicyMinReviewersSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersSettingsObservation) DeepCopyInto(out *PolicyMinReviewersSettingsObservation) {
	*out = *in
	if in.AllowCompletionWithRejectsOrWaits != nil {
		in, out := &in.AllowCompletionWithRejectsOrWaits, &out.AllowCompletionWithRejectsOrWaits
		*out = new(bool)
		**out = **in
	}
	if in.LastPusherCannotApprove != nil {
		in, out := &in.LastPusherCannotApprove, &out.LastPusherCannotApprove
		*out = new(bool)
		**out = **in
	}
	if in.OnLastIterationRequireVote != nil {
		in, out := &in.OnLastIterationRequireVote, &out.OnLastIterationRequireVote
		*out = new(bool)
		**out = **in
	}
	if in.OnPushResetAllVotes != nil {
		in, out := &in.OnPushResetAllVotes, &out.OnPushResetAllVotes
		*out = new(bool)
		**out = **in
	}
	if in.OnPushResetApprovedVotes != nil {
		in, out := &in.OnPushResetApprovedVotes, &out.OnPushResetApprovedVotes
		*out = new(bool)
		**out = **in
	}
	if in.ReviewerCount != nil {
		in, out := &in.ReviewerCount, &out.ReviewerCount
		*out = new(float64)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyMinReviewersSettingsScopeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubmitterCanVote != nil {
		in, out := &in.SubmitterCanVote, &out.SubmitterCanVote
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersSettingsObservation.
func (in *PolicyMinReviewersSettingsObservation) DeepCopy() *PolicyMinReviewersSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersSettingsParameters) DeepCopyInto(out *PolicyMinReviewersSettingsParameters) {
	*out = *in
	if in.AllowCompletionWithRejectsOrWaits != nil {
		in, out := &in.AllowCompletionWithRejectsOrWaits, &out.AllowCompletionWithRejectsOrWaits
		*out = new(bool)
		**out = **in
	}
	if in.LastPusherCannotApprove != nil {
		in, out := &in.LastPusherCannotApprove, &out.LastPusherCannotApprove
		*out = new(bool)
		**out = **in
	}
	if in.OnLastIterationRequireVote != nil {
		in, out := &in.OnLastIterationRequireVote, &out.OnLastIterationRequireVote
		*out = new(bool)
		**out = **in
	}
	if in.OnPushResetAllVotes != nil {
		in, out := &in.OnPushResetAllVotes, &out.OnPushResetAllVotes
		*out = new(bool)
		**out = **in
	}
	if in.OnPushResetApprovedVotes != nil {
		in, out := &in.OnPushResetApprovedVotes, &out.OnPushResetApprovedVotes
		*out = new(bool)
		**out = **in
	}
	if in.ReviewerCount != nil {
		in, out := &in.ReviewerCount, &out.ReviewerCount
		*out = new(float64)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyMinReviewersSettingsScopeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubmitterCanVote != nil {
		in, out := &in.SubmitterCanVote, &out.SubmitterCanVote
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersSettingsParameters.
func (in *PolicyMinReviewersSettingsParameters) DeepCopy() *PolicyMinReviewersSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersSettingsScopeInitParameters) DeepCopyInto(out *PolicyMinReviewersSettingsScopeInitParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersSettingsScopeInitParameters.
func (in *PolicyMinReviewersSettingsScopeInitParameters) DeepCopy() *PolicyMinReviewersSettingsScopeInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersSettingsScopeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersSettingsScopeObservation) DeepCopyInto(out *PolicyMinReviewersSettingsScopeObservation) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersSettingsScopeObservation.
func (in *PolicyMinReviewersSettingsScopeObservation) DeepCopy() *PolicyMinReviewersSettingsScopeObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersSettingsScopeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersSettingsScopeParameters) DeepCopyInto(out *PolicyMinReviewersSettingsScopeParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersSettingsScopeParameters.
func (in *PolicyMinReviewersSettingsScopeParameters) DeepCopy() *PolicyMinReviewersSettingsScopeParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersSettingsScopeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersSpec) DeepCopyInto(out *PolicyMinReviewersSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersSpec.
func (in *PolicyMinReviewersSpec) DeepCopy() *PolicyMinReviewersSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMinReviewersStatus) DeepCopyInto(out *PolicyMinReviewersStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMinReviewersStatus.
func (in *PolicyMinReviewersStatus) DeepCopy() *PolicyMinReviewersStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyMinReviewersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheck) DeepCopyInto(out *PolicyStatusCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheck.
func (in *PolicyStatusCheck) DeepCopy() *PolicyStatusCheck {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyStatusCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckInitParameters) DeepCopyInto(out *PolicyStatusCheckInitParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyStatusCheckSettingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckInitParameters.
func (in *PolicyStatusCheckInitParameters) DeepCopy() *PolicyStatusCheckInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckList) DeepCopyInto(out *PolicyStatusCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyStatusCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckList.
func (in *PolicyStatusCheckList) DeepCopy() *PolicyStatusCheckList {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyStatusCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckObservation) DeepCopyInto(out *PolicyStatusCheckObservation) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyStatusCheckSettingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckObservation.
func (in *PolicyStatusCheckObservation) DeepCopy() *PolicyStatusCheckObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckParameters) DeepCopyInto(out *PolicyStatusCheckParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyStatusCheckSettingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckParameters.
func (in *PolicyStatusCheckParameters) DeepCopy() *PolicyStatusCheckParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckSettingsInitParameters) DeepCopyInto(out *PolicyStatusCheckSettingsInitParameters) {
	*out = *in
	if in.Applicability != nil {
		in, out := &in.Applicability, &out.Applicability
		*out = new(string)
		**out = **in
	}
	if in.AuthorID != nil {
		in, out := &in.AuthorID, &out.AuthorID
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FilenamePatterns != nil {
		in, out := &in.FilenamePatterns, &out.FilenamePatterns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Genre != nil {
		in, out := &in.Genre, &out.Genre
		*out = new(string)
		**out = **in
	}
	if in.InvalidateOnUpdate != nil {
		in, out := &in.InvalidateOnUpdate, &out.InvalidateOnUpdate
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyStatusCheckSettingsScopeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckSettingsInitParameters.
func (in *PolicyStatusCheckSettingsInitParameters) DeepCopy() *PolicyStatusCheckSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckSettingsObservation) DeepCopyInto(out *PolicyStatusCheckSettingsObservation) {
	*out = *in
	if in.Applicability != nil {
		in, out := &in.Applicability, &out.Applicability
		*out = new(string)
		**out = **in
	}
	if in.AuthorID != nil {
		in, out := &in.AuthorID, &out.AuthorID
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FilenamePatterns != nil {
		in, out := &in.FilenamePatterns, &out.FilenamePatterns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Genre != nil {
		in, out := &in.Genre, &out.Genre
		*out = new(string)
		**out = **in
	}
	if in.InvalidateOnUpdate != nil {
		in, out := &in.InvalidateOnUpdate, &out.InvalidateOnUpdate
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyStatusCheckSettingsScopeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckSettingsObservation.
func (in *PolicyStatusCheckSettingsObservation) DeepCopy() *PolicyStatusCheckSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckSettingsParameters) DeepCopyInto(out *PolicyStatusCheckSettingsParameters) {
	*out = *in
	if in.Applicability != nil {
		in, out := &in.Applicability, &out.Applicability
		*out = new(string)
		**out = **in
	}
	if in.AuthorID != nil {
		in, out := &in.AuthorID, &out.AuthorID
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FilenamePatterns != nil {
		in, out := &in.FilenamePatterns, &out.FilenamePatterns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Genre != nil {
		in, out := &in.Genre, &out.Genre
		*out = new(string)
		**out = **in
	}
	if in.InvalidateOnUpdate != nil {
		in, out := &in.InvalidateOnUpdate, &out.InvalidateOnUpdate
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyStatusCheckSettingsScopeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckSettingsParameters.
func (in *PolicyStatusCheckSettingsParameters) DeepCopy() *PolicyStatusCheckSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckSettingsScopeInitParameters) DeepCopyInto(out *PolicyStatusCheckSettingsScopeInitParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckSettingsScopeInitParameters.
func (in *PolicyStatusCheckSettingsScopeInitParameters) DeepCopy() *PolicyStatusCheckSettingsScopeInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckSettingsScopeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckSettingsScopeObservation) DeepCopyInto(out *PolicyStatusCheckSettingsScopeObservation) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckSettingsScopeObservation.
func (in *PolicyStatusCheckSettingsScopeObservation) DeepCopy() *PolicyStatusCheckSettingsScopeObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckSettingsScopeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckSettingsScopeParameters) DeepCopyInto(out *PolicyStatusCheckSettingsScopeParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckSettingsScopeParameters.
func (in *PolicyStatusCheckSettingsScopeParameters) DeepCopy() *PolicyStatusCheckSettingsScopeParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckSettingsScopeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckSpec) DeepCopyInto(out *PolicyStatusCheckSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckSpec.
func (in *PolicyStatusCheckSpec) DeepCopy() *PolicyStatusCheckSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatusCheckStatus) DeepCopyInto(out *PolicyStatusCheckStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatusCheckStatus.
func (in *PolicyStatusCheckStatus) DeepCopy() *PolicyStatusCheckStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatusCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinking) DeepCopyInto(out *PolicyWorkItemLinking) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinking.
func (in *PolicyWorkItemLinking) DeepCopy() *PolicyWorkItemLinking {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyWorkItemLinking) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingInitParameters) DeepCopyInto(out *PolicyWorkItemLinkingInitParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyWorkItemLinkingSettingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingInitParameters.
func (in *PolicyWorkItemLinkingInitParameters) DeepCopy() *PolicyWorkItemLinkingInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingList) DeepCopyInto(out *PolicyWorkItemLinkingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyWorkItemLinking, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingList.
func (in *PolicyWorkItemLinkingList) DeepCopy() *PolicyWorkItemLinkingList {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyWorkItemLinkingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingObservation) DeepCopyInto(out *PolicyWorkItemLinkingObservation) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyWorkItemLinkingSettingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingObservation.
func (in *PolicyWorkItemLinkingObservation) DeepCopy() *PolicyWorkItemLinkingObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingParameters) DeepCopyInto(out *PolicyWorkItemLinkingParameters) {
	*out = *in
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]PolicyWorkItemLinkingSettingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingParameters.
func (in *PolicyWorkItemLinkingParameters) DeepCopy() *PolicyWorkItemLinkingParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingSettingsInitParameters) DeepCopyInto(out *PolicyWorkItemLinkingSettingsInitParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyWorkItemLinkingSettingsScopeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingSettingsInitParameters.
func (in *PolicyWorkItemLinkingSettingsInitParameters) DeepCopy() *PolicyWorkItemLinkingSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingSettingsObservation) DeepCopyInto(out *PolicyWorkItemLinkingSettingsObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyWorkItemLinkingSettingsScopeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingSettingsObservation.
func (in *PolicyWorkItemLinkingSettingsObservation) DeepCopy() *PolicyWorkItemLinkingSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingSettingsParameters) DeepCopyInto(out *PolicyWorkItemLinkingSettingsParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]PolicyWorkItemLinkingSettingsScopeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingSettingsParameters.
func (in *PolicyWorkItemLinkingSettingsParameters) DeepCopy() *PolicyWorkItemLinkingSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingSettingsScopeInitParameters) DeepCopyInto(out *PolicyWorkItemLinkingSettingsScopeInitParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingSettingsScopeInitParameters.
func (in *PolicyWorkItemLinkingSettingsScopeInitParameters) DeepCopy() *PolicyWorkItemLinkingSettingsScopeInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingSettingsScopeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingSettingsScopeObservation) DeepCopyInto(out *PolicyWorkItemLinkingSettingsScopeObservation) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingSettingsScopeObservation.
func (in *PolicyWorkItemLinkingSettingsScopeObservation) DeepCopy() *PolicyWorkItemLinkingSettingsScopeObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingSettingsScopeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingSettingsScopeParameters) DeepCopyInto(out *PolicyWorkItemLinkingSettingsScopeParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingSettingsScopeParameters.
func (in *PolicyWorkItemLinkingSettingsScopeParameters) DeepCopy() *PolicyWorkItemLinkingSettingsScopeParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingSettingsScopeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingSpec) DeepCopyInto(out *PolicyWorkItemLinkingSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingSpec.
func (in *PolicyWorkItemLinkingSpec) DeepCopy() *PolicyWorkItemLinkingSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyWorkItemLinkingStatus) DeepCopyInto(out *PolicyWorkItemLinkingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyWorkItemLinkingStatus.
func (in *PolicyWorkItemLinkingStatus) DeepCopy() *PolicyWorkItemLinkingStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyWorkItemLinkingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeInitParameters) DeepCopyInto(out *ScopeInitParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeInitParameters.
func (in *ScopeInitParameters) DeepCopy() *ScopeInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScopeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeObservation) DeepCopyInto(out *ScopeObservation) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeObservation.
func (in *ScopeObservation) DeepCopy() *ScopeObservation {
	if in == nil {
		return nil
	}
	out := new(ScopeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeParameters) DeepCopyInto(out *ScopeParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeParameters.
func (in *ScopeParameters) DeepCopy() *ScopeParameters {
	if in == nil {
		return nil
	}
	out := new(ScopeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsInitParameters) DeepCopyInto(out *SettingsInitParameters) {
	*out = *in
	if in.AutoReviewerIds != nil {
		in, out := &in.AutoReviewerIds, &out.AutoReviewerIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.MinimumNumberOfReviewers != nil {
		in, out := &in.MinimumNumberOfReviewers, &out.MinimumNumberOfReviewers
		*out = new(float64)
		**out = **in
	}
	if in.PathFilters != nil {
		in, out := &in.PathFilters, &out.PathFilters
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]ScopeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubmitterCanVote != nil {
		in, out := &in.SubmitterCanVote, &out.SubmitterCanVote
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsInitParameters.
func (in *SettingsInitParameters) DeepCopy() *SettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsObservation) DeepCopyInto(out *SettingsObservation) {
	*out = *in
	if in.AutoReviewerIds != nil {
		in, out := &in.AutoReviewerIds, &out.AutoReviewerIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.MinimumNumberOfReviewers != nil {
		in, out := &in.MinimumNumberOfReviewers, &out.MinimumNumberOfReviewers
		*out = new(float64)
		**out = **in
	}
	if in.PathFilters != nil {
		in, out := &in.PathFilters, &out.PathFilters
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]ScopeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubmitterCanVote != nil {
		in, out := &in.SubmitterCanVote, &out.SubmitterCanVote
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsObservation.
func (in *SettingsObservation) DeepCopy() *SettingsObservation {
	if in == nil {
		return nil
	}
	out := new(SettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsParameters) DeepCopyInto(out *SettingsParameters) {
	*out = *in
	if in.AutoReviewerIds != nil {
		in, out := &in.AutoReviewerIds, &out.AutoReviewerIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.MinimumNumberOfReviewers != nil {
		in, out := &in.MinimumNumberOfReviewers, &out.MinimumNumberOfReviewers
		*out = new(float64)
		**out = **in
	}
	if in.PathFilters != nil {
		in, out := &in.PathFilters, &out.PathFilters
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]ScopeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubmitterCanVote != nil {
		in, out := &in.SubmitterCanVote, &out.SubmitterCanVote
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsParameters.
func (in *SettingsParameters) DeepCopy() *SettingsParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsScopeInitParameters) DeepCopyInto(out *SettingsScopeInitParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsScopeInitParameters.
func (in *SettingsScopeInitParameters) DeepCopy() *SettingsScopeInitParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsScopeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsScopeObservation) DeepCopyInto(out *SettingsScopeObservation) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsScopeObservation.
func (in *SettingsScopeObservation) DeepCopy() *SettingsScopeObservation {
	if in == nil {
		return nil
	}
	out := new(SettingsScopeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsScopeParameters) DeepCopyInto(out *SettingsScopeParameters) {
	*out = *in
	if in.MatchType != nil {
		in, out := &in.MatchType, &out.MatchType
		*out = new(string)
		**out = **in
	}
	if in.RepositoryID != nil {
		in, out := &in.RepositoryID, &out.RepositoryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsScopeParameters.
func (in *SettingsScopeParameters) DeepCopy() *SettingsScopeParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsScopeParameters)
	in.DeepCopyInto(out)
	return out
}
