// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PolicyAutoReviewersInitParameters struct {

	// A flag indicating if the policy should be blocking. This relates to the Azure DevOps terms "optional" and "required" reviewers. Defaults to true.
	Blocking *bool `json:"blocking,omitempty" tf:"blocking,omitempty"`

	// A flag indicating if the policy should be enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the project in which the policy will be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Configuration for the policy. This block must be defined exactly once.
	Settings []SettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`
}

type PolicyAutoReviewersObservation struct {

	// A flag indicating if the policy should be blocking. This relates to the Azure DevOps terms "optional" and "required" reviewers. Defaults to true.
	Blocking *bool `json:"blocking,omitempty" tf:"blocking,omitempty"`

	// A flag indicating if the policy should be enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of branch policy configuration.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project in which the policy will be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Configuration for the policy. This block must be defined exactly once.
	Settings []SettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`
}

type PolicyAutoReviewersParameters struct {

	// A flag indicating if the policy should be blocking. This relates to the Azure DevOps terms "optional" and "required" reviewers. Defaults to true.
	// +kubebuilder:validation:Optional
	Blocking *bool `json:"blocking,omitempty" tf:"blocking,omitempty"`

	// A flag indicating if the policy should be enabled. Defaults to true.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the project in which the policy will be created.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Configuration for the policy. This block must be defined exactly once.
	// +kubebuilder:validation:Optional
	Settings []SettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`
}

type ScopeInitParameters struct {

	// The match type to use when applying the policy. Supported values are Exact (default), Prefix or DefaultBranch.
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// The repository ID. Needed only if the scope of the policy will be limited to a single repository. If match_type is DefaultBranch, this should not be defined.
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// The ref pattern to use for the match when match_type other than DefaultBranch. If match_type is Exact, this should be a qualified ref such as refs/heads/master. If match_type is Prefix, this should be a ref path such as refs/heads/releases.
	RepositoryRef *string `json:"repositoryRef,omitempty" tf:"repository_ref,omitempty"`
}

type ScopeObservation struct {

	// The match type to use when applying the policy. Supported values are Exact (default), Prefix or DefaultBranch.
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// The repository ID. Needed only if the scope of the policy will be limited to a single repository. If match_type is DefaultBranch, this should not be defined.
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// The ref pattern to use for the match when match_type other than DefaultBranch. If match_type is Exact, this should be a qualified ref such as refs/heads/master. If match_type is Prefix, this should be a ref path such as refs/heads/releases.
	RepositoryRef *string `json:"repositoryRef,omitempty" tf:"repository_ref,omitempty"`
}

type ScopeParameters struct {

	// The match type to use when applying the policy. Supported values are Exact (default), Prefix or DefaultBranch.
	// +kubebuilder:validation:Optional
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// The repository ID. Needed only if the scope of the policy will be limited to a single repository. If match_type is DefaultBranch, this should not be defined.
	// +kubebuilder:validation:Optional
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// The ref pattern to use for the match when match_type other than DefaultBranch. If match_type is Exact, this should be a qualified ref such as refs/heads/master. If match_type is Prefix, this should be a ref path such as refs/heads/releases.
	// +kubebuilder:validation:Optional
	RepositoryRef *string `json:"repositoryRef,omitempty" tf:"repository_ref,omitempty"`
}

type SettingsInitParameters struct {

	// Required reviewers ids. Supports multiples user Ids.
	AutoReviewerIds []*string `json:"autoReviewerIds,omitempty" tf:"auto_reviewer_ids,omitempty"`

	// Activity feed message, Message will appear in the activity feed of pull requests with automatically added reviewers.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// Minimum number of required reviewers. Defaults to 1.
	MinimumNumberOfReviewers *float64 `json:"minimumNumberOfReviewers,omitempty" tf:"minimum_number_of_reviewers,omitempty"`

	// Filter path(s) on which the policy is applied. Supports absolute paths, wildcards and multiple paths. Example: /WebApp/Models/Data.cs, /WebApp/* or *.cs,/WebApp/Models/Data.cs;ClientApp/Models/Data.cs.
	PathFilters []*string `json:"pathFilters,omitempty" tf:"path_filters,omitempty"`

	// Controls which repositories and branches the policy will be enabled for. This block must be defined at least once.
	Scope []ScopeInitParameters `json:"scope,omitempty" tf:"scope,omitempty"`

	// Controls whether or not the submitter's vote counts. Defaults to false.
	SubmitterCanVote *bool `json:"submitterCanVote,omitempty" tf:"submitter_can_vote,omitempty"`
}

type SettingsObservation struct {

	// Required reviewers ids. Supports multiples user Ids.
	AutoReviewerIds []*string `json:"autoReviewerIds,omitempty" tf:"auto_reviewer_ids,omitempty"`

	// Activity feed message, Message will appear in the activity feed of pull requests with automatically added reviewers.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// Minimum number of required reviewers. Defaults to 1.
	MinimumNumberOfReviewers *float64 `json:"minimumNumberOfReviewers,omitempty" tf:"minimum_number_of_reviewers,omitempty"`

	// Filter path(s) on which the policy is applied. Supports absolute paths, wildcards and multiple paths. Example: /WebApp/Models/Data.cs, /WebApp/* or *.cs,/WebApp/Models/Data.cs;ClientApp/Models/Data.cs.
	PathFilters []*string `json:"pathFilters,omitempty" tf:"path_filters,omitempty"`

	// Controls which repositories and branches the policy will be enabled for. This block must be defined at least once.
	Scope []ScopeObservation `json:"scope,omitempty" tf:"scope,omitempty"`

	// Controls whether or not the submitter's vote counts. Defaults to false.
	SubmitterCanVote *bool `json:"submitterCanVote,omitempty" tf:"submitter_can_vote,omitempty"`
}

type SettingsParameters struct {

	// Required reviewers ids. Supports multiples user Ids.
	// +kubebuilder:validation:Optional
	AutoReviewerIds []*string `json:"autoReviewerIds" tf:"auto_reviewer_ids,omitempty"`

	// Activity feed message, Message will appear in the activity feed of pull requests with automatically added reviewers.
	// +kubebuilder:validation:Optional
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// Minimum number of required reviewers. Defaults to 1.
	// +kubebuilder:validation:Optional
	MinimumNumberOfReviewers *float64 `json:"minimumNumberOfReviewers,omitempty" tf:"minimum_number_of_reviewers,omitempty"`

	// Filter path(s) on which the policy is applied. Supports absolute paths, wildcards and multiple paths. Example: /WebApp/Models/Data.cs, /WebApp/* or *.cs,/WebApp/Models/Data.cs;ClientApp/Models/Data.cs.
	// +kubebuilder:validation:Optional
	PathFilters []*string `json:"pathFilters,omitempty" tf:"path_filters,omitempty"`

	// Controls which repositories and branches the policy will be enabled for. This block must be defined at least once.
	// +kubebuilder:validation:Optional
	Scope []ScopeParameters `json:"scope" tf:"scope,omitempty"`

	// Controls whether or not the submitter's vote counts. Defaults to false.
	// +kubebuilder:validation:Optional
	SubmitterCanVote *bool `json:"submitterCanVote,omitempty" tf:"submitter_can_vote,omitempty"`
}

// PolicyAutoReviewersSpec defines the desired state of PolicyAutoReviewers
type PolicyAutoReviewersSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PolicyAutoReviewersParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyAutoReviewersInitParameters `json:"initProvider,omitempty"`
}

// PolicyAutoReviewersStatus defines the observed state of PolicyAutoReviewers.
type PolicyAutoReviewersStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyAutoReviewersObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyAutoReviewers is the Schema for the PolicyAutoReviewerss API. Manages required reviewer policy branch policy within Azure DevOps project.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type PolicyAutoReviewers struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settings) || (has(self.initProvider) && has(self.initProvider.settings))",message="spec.forProvider.settings is a required parameter"
	Spec   PolicyAutoReviewersSpec   `json:"spec"`
	Status PolicyAutoReviewersStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyAutoReviewersList contains a list of PolicyAutoReviewerss
type PolicyAutoReviewersList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyAutoReviewers `json:"items"`
}

// Repository type metadata.
var (
	PolicyAutoReviewers_Kind             = "PolicyAutoReviewers"
	PolicyAutoReviewers_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyAutoReviewers_Kind}.String()
	PolicyAutoReviewers_KindAPIVersion   = PolicyAutoReviewers_Kind + "." + CRDGroupVersion.String()
	PolicyAutoReviewers_GroupVersionKind = CRDGroupVersion.WithKind(PolicyAutoReviewers_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyAutoReviewers{}, &PolicyAutoReviewersList{})
}
