apiVersion: git.azuredevops.m.crossplane.io/v1alpha1
kind: RepositoryBranch
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/repositorybranch
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    name: example-branch-name
    refBranch: ${azuredevops_git_repository.example.default_branch}
    repositoryId: ${azuredevops_git_repository.example.id}

---

apiVersion: git.azuredevops.m.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/repositorybranch
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Git Repository
    projectId: ${azuredevops_project.example.id}

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/repositorybranch
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
