// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ResourceKubernetesInitParameters struct {

	// A cluster name for the Kubernetes Resource.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// The ID of the environment under which to create the Kubernetes Resource.
	EnvironmentID *float64 `json:"environmentId,omitempty" tf:"environment_id,omitempty"`

	// The name for the Kubernetes Resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespace for the Kubernetes Resource.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the service endpoint to associate with the Kubernetes Resource.
	ServiceEndpointID *string `json:"serviceEndpointId,omitempty" tf:"service_endpoint_id,omitempty"`

	// A set of tags for the Kubernetes Resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ResourceKubernetesObservation struct {

	// A cluster name for the Kubernetes Resource.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// The ID of the environment under which to create the Kubernetes Resource.
	EnvironmentID *float64 `json:"environmentId,omitempty" tf:"environment_id,omitempty"`

	// The ID of the Kubernetes Resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name for the Kubernetes Resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespace for the Kubernetes Resource.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the service endpoint to associate with the Kubernetes Resource.
	ServiceEndpointID *string `json:"serviceEndpointId,omitempty" tf:"service_endpoint_id,omitempty"`

	// A set of tags for the Kubernetes Resource.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ResourceKubernetesParameters struct {

	// A cluster name for the Kubernetes Resource.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// The ID of the environment under which to create the Kubernetes Resource.
	// +kubebuilder:validation:Optional
	EnvironmentID *float64 `json:"environmentId,omitempty" tf:"environment_id,omitempty"`

	// The name for the Kubernetes Resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespace for the Kubernetes Resource.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The ID of the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the service endpoint to associate with the Kubernetes Resource.
	// +kubebuilder:validation:Optional
	ServiceEndpointID *string `json:"serviceEndpointId,omitempty" tf:"service_endpoint_id,omitempty"`

	// A set of tags for the Kubernetes Resource.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// ResourceKubernetesSpec defines the desired state of ResourceKubernetes
type ResourceKubernetesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ResourceKubernetesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ResourceKubernetesInitParameters `json:"initProvider,omitempty"`
}

// ResourceKubernetesStatus defines the observed state of ResourceKubernetes.
type ResourceKubernetesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ResourceKubernetesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ResourceKubernetes is the Schema for the ResourceKubernetess API. Manages a Kubernetes Resource for an Environment.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type ResourceKubernetes struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environmentId) || (has(self.initProvider) && has(self.initProvider.environmentId))",message="spec.forProvider.environmentId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__namespace__) || (has(self.initProvider) && has(self.initProvider.__namespace__))",message="spec.forProvider.namespace is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointId) || (has(self.initProvider) && has(self.initProvider.serviceEndpointId))",message="spec.forProvider.serviceEndpointId is a required parameter"
	Spec   ResourceKubernetesSpec   `json:"spec"`
	Status ResourceKubernetesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ResourceKubernetesList contains a list of ResourceKubernetess
type ResourceKubernetesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ResourceKubernetes `json:"items"`
}

// Repository type metadata.
var (
	ResourceKubernetes_Kind             = "ResourceKubernetes"
	ResourceKubernetes_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ResourceKubernetes_Kind}.String()
	ResourceKubernetes_KindAPIVersion   = ResourceKubernetes_Kind + "." + CRDGroupVersion.String()
	ResourceKubernetes_GroupVersionKind = CRDGroupVersion.WithKind(ResourceKubernetes_Kind)
)

func init() {
	SchemeBuilder.Register(&ResourceKubernetes{}, &ResourceKubernetesList{})
}
