apiVersion: other.azuredevops.crossplane.io/v1alpha1
kind: Assignment
metadata:
  annotations:
    meta.upbound.io/example-id: other/v1alpha1/assignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    identityId: ${azuredevops_group.example.origin_id}
    resourceId: ${format("%s_%s", azuredevops_project.example.id, azuredevops_environment.example.id)}
    roleName: Administrator
    scope: distributedtask.environmentreferencerole

---

apiVersion: environment.azuredevops.crossplane.io/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: other/v1alpha1/assignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Example pipeline deployment environment
    name: Example Environment
    projectId: ${azuredevops_project.example.id}

---

apiVersion: group.azuredevops.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: other/v1alpha1/assignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Description of example group
    displayName: Example group
    scope: ${azuredevops_project.example.id}

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: other/v1alpha1/assignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
