apiVersion: wiki.azuredevops.crossplane.io/v1alpha1
kind: Wiki
metadata:
  annotations:
    meta.upbound.io/example-id: wiki/v1alpha1/wiki
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: 'Example project wiki '
    projectId: ${azuredevops_project.example.id}
    type: projectWiki

---

apiVersion: git.azuredevops.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: wiki/v1alpha1/wiki
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Repository
    projectId: ${azuredevops_project.example.id}

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: wiki/v1alpha1/wiki
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
