// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PolicyCheckCredentialsInitParameters struct {

	// A flag indicating if the policy should be blocking. Defaults to true.
	Blocking *bool `json:"blocking,omitempty" tf:"blocking,omitempty"`

	// A flag indicating if the policy should be enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the project in which the policy will be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Control whether the policy is enabled for the repository or the project. If repository_ids not configured, the policy will be set to the project.
	RepositoryIds []*string `json:"repositoryIds,omitempty" tf:"repository_ids,omitempty"`
}

type PolicyCheckCredentialsObservation struct {

	// A flag indicating if the policy should be blocking. Defaults to true.
	Blocking *bool `json:"blocking,omitempty" tf:"blocking,omitempty"`

	// A flag indicating if the policy should be enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the repository policy.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project in which the policy will be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Control whether the policy is enabled for the repository or the project. If repository_ids not configured, the policy will be set to the project.
	RepositoryIds []*string `json:"repositoryIds,omitempty" tf:"repository_ids,omitempty"`
}

type PolicyCheckCredentialsParameters struct {

	// A flag indicating if the policy should be blocking. Defaults to true.
	// +kubebuilder:validation:Optional
	Blocking *bool `json:"blocking,omitempty" tf:"blocking,omitempty"`

	// A flag indicating if the policy should be enabled. Defaults to true.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the project in which the policy will be created.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Control whether the policy is enabled for the repository or the project. If repository_ids not configured, the policy will be set to the project.
	// +kubebuilder:validation:Optional
	RepositoryIds []*string `json:"repositoryIds,omitempty" tf:"repository_ids,omitempty"`
}

// PolicyCheckCredentialsSpec defines the desired state of PolicyCheckCredentials
type PolicyCheckCredentialsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PolicyCheckCredentialsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyCheckCredentialsInitParameters `json:"initProvider,omitempty"`
}

// PolicyCheckCredentialsStatus defines the observed state of PolicyCheckCredentials.
type PolicyCheckCredentialsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyCheckCredentialsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyCheckCredentials is the Schema for the PolicyCheckCredentialss API. Manage a credentials check repository policy within Azure DevOps project.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type PolicyCheckCredentials struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   PolicyCheckCredentialsSpec   `json:"spec"`
	Status PolicyCheckCredentialsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyCheckCredentialsList contains a list of PolicyCheckCredentialss
type PolicyCheckCredentialsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyCheckCredentials `json:"items"`
}

// Repository type metadata.
var (
	PolicyCheckCredentials_Kind             = "PolicyCheckCredentials"
	PolicyCheckCredentials_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyCheckCredentials_Kind}.String()
	PolicyCheckCredentials_KindAPIVersion   = PolicyCheckCredentials_Kind + "." + CRDGroupVersion.String()
	PolicyCheckCredentials_GroupVersionKind = CRDGroupVersion.WithKind(PolicyCheckCredentials_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyCheckCredentials{}, &PolicyCheckCredentialsList{})
}
