// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AuthPersonalInitParameters struct {

	// The Personal Access Token for Azure DevOps Organization.
	// Personal access tokens are applicable only for connections targeting Azure DevOps organization or TFS 2017 (and higher)
	PersonalAccessTokenSecretRef v1.LocalSecretKeySelector `json:"personalAccessTokenSecretRef" tf:"-"`
}

type AuthPersonalObservation struct {
}

type AuthPersonalParameters struct {

	// The Personal Access Token for Azure DevOps Organization.
	// Personal access tokens are applicable only for connections targeting Azure DevOps organization or TFS 2017 (and higher)
	// +kubebuilder:validation:Optional
	PersonalAccessTokenSecretRef v1.LocalSecretKeySelector `json:"personalAccessTokenSecretRef" tf:"-"`
}

type ExternaltfsInitParameters struct {

	// An auth_personal block as documented below. Allows connecting using a personal access token.
	AuthPersonal []AuthPersonalInitParameters `json:"authPersonal,omitempty" tf:"auth_personal,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// Azure DevOps Organization or TFS Project Collection Url.
	// URL of the Azure DevOps organization or the TFS Project Collection to connect to.
	ConnectionURL *string `json:"connectionUrl,omitempty" tf:"connection_url,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

type ExternaltfsObservation struct {

	// An auth_personal block as documented below. Allows connecting using a personal access token.
	AuthPersonal []AuthPersonalParameters `json:"authPersonal,omitempty" tf:"auth_personal,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// Azure DevOps Organization or TFS Project Collection Url.
	// URL of the Azure DevOps organization or the TFS Project Collection to connect to.
	ConnectionURL *string `json:"connectionUrl,omitempty" tf:"connection_url,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

type ExternaltfsParameters struct {

	// An auth_personal block as documented below. Allows connecting using a personal access token.
	// +kubebuilder:validation:Optional
	AuthPersonal []AuthPersonalParameters `json:"authPersonal,omitempty" tf:"auth_personal,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// Azure DevOps Organization or TFS Project Collection Url.
	// URL of the Azure DevOps organization or the TFS Project Collection to connect to.
	// +kubebuilder:validation:Optional
	ConnectionURL *string `json:"connectionUrl,omitempty" tf:"connection_url,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The Service Endpoint name.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

// ExternaltfsSpec defines the desired state of Externaltfs
type ExternaltfsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ExternaltfsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ExternaltfsInitParameters `json:"initProvider,omitempty"`
}

// ExternaltfsStatus defines the observed state of Externaltfs.
type ExternaltfsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ExternaltfsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Externaltfs is the Schema for the Externaltfss API. Manages an Azure Repos/Team Foundation Server service endpoint within Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type Externaltfs struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authPersonal) || (has(self.initProvider) && has(self.initProvider.authPersonal))",message="spec.forProvider.authPersonal is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.connectionUrl) || (has(self.initProvider) && has(self.initProvider.connectionUrl))",message="spec.forProvider.connectionUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	Spec   ExternaltfsSpec   `json:"spec"`
	Status ExternaltfsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExternaltfsList contains a list of Externaltfss
type ExternaltfsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Externaltfs `json:"items"`
}

// Repository type metadata.
var (
	Externaltfs_Kind             = "Externaltfs"
	Externaltfs_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Externaltfs_Kind}.String()
	Externaltfs_KindAPIVersion   = Externaltfs_Kind + "." + CRDGroupVersion.String()
	Externaltfs_GroupVersionKind = CRDGroupVersion.WithKind(Externaltfs_Kind)
)

func init() {
	SchemeBuilder.Register(&Externaltfs{}, &ExternaltfsList{})
}
