// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GenericGitInitParameters struct {

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A value indicating whether or not to attempt accessing this git server from Azure Pipelines.
	// A value indicating whether or not to attempt accessing this git server from Azure Pipelines.
	EnablePipelinesAccess *bool `json:"enablePipelinesAccess,omitempty" tf:"enable_pipelines_access,omitempty"`

	// The PAT or password used to authenticate to the git repository.
	// The password or token key to use for the GenericGit git service connection.
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The URL of the repository associated with the service endpoint.
	// The server URL of the GenericGit git service connection.
	RepositoryURL *string `json:"repositoryUrl,omitempty" tf:"repository_url,omitempty"`

	// The name of the service endpoint.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The username used to authenticate to the git repository.
	// The username to use for the GenericGit service git connection.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type GenericGitObservation struct {

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A value indicating whether or not to attempt accessing this git server from Azure Pipelines.
	// A value indicating whether or not to attempt accessing this git server from Azure Pipelines.
	EnablePipelinesAccess *bool `json:"enablePipelinesAccess,omitempty" tf:"enable_pipelines_access,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The URL of the repository associated with the service endpoint.
	// The server URL of the GenericGit git service connection.
	RepositoryURL *string `json:"repositoryUrl,omitempty" tf:"repository_url,omitempty"`

	// The name of the service endpoint.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The username used to authenticate to the git repository.
	// The username to use for the GenericGit service git connection.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type GenericGitParameters struct {

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A value indicating whether or not to attempt accessing this git server from Azure Pipelines.
	// A value indicating whether or not to attempt accessing this git server from Azure Pipelines.
	// +kubebuilder:validation:Optional
	EnablePipelinesAccess *bool `json:"enablePipelinesAccess,omitempty" tf:"enable_pipelines_access,omitempty"`

	// The PAT or password used to authenticate to the git repository.
	// The password or token key to use for the GenericGit git service connection.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The ID of the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The URL of the repository associated with the service endpoint.
	// The server URL of the GenericGit git service connection.
	// +kubebuilder:validation:Optional
	RepositoryURL *string `json:"repositoryUrl,omitempty" tf:"repository_url,omitempty"`

	// The name of the service endpoint.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The username used to authenticate to the git repository.
	// The username to use for the GenericGit service git connection.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// GenericGitSpec defines the desired state of GenericGit
type GenericGitSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GenericGitParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GenericGitInitParameters `json:"initProvider,omitempty"`
}

// GenericGitStatus defines the observed state of GenericGit.
type GenericGitStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GenericGitObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GenericGit is the Schema for the GenericGits API. Manages a generic service endpoint within Azure DevOps, which can be used to authenticate to any external git service using basic authentication via a username and password.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type GenericGit struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repositoryUrl) || (has(self.initProvider) && has(self.initProvider.repositoryUrl))",message="spec.forProvider.repositoryUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	Spec   GenericGitSpec   `json:"spec"`
	Status GenericGitStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GenericGitList contains a list of GenericGits
type GenericGitList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GenericGit `json:"items"`
}

// Repository type metadata.
var (
	GenericGit_Kind             = "GenericGit"
	GenericGit_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GenericGit_Kind}.String()
	GenericGit_KindAPIVersion   = GenericGit_Kind + "." + CRDGroupVersion.String()
	GenericGit_GroupVersionKind = CRDGroupVersion.WithKind(GenericGit_Kind)
)

func init() {
	SchemeBuilder.Register(&GenericGit{}, &GenericGitList{})
}
