// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type MavenAuthenticationBasicInitParameters struct {

	// The password Maven Repository.
	// The Maven password.
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The Username of the Maven Repository.
	// The Maven user name.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type MavenAuthenticationBasicObservation struct {

	// The Username of the Maven Repository.
	// The Maven user name.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type MavenAuthenticationBasicParameters struct {

	// The password Maven Repository.
	// The Maven password.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The Username of the Maven Repository.
	// The Maven user name.
	// +kubebuilder:validation:Optional
	Username *string `json:"username" tf:"username,omitempty"`
}

type MavenAuthenticationTokenInitParameters struct {

	// Authentication Token generated through maven repository.
	// The Maven access token.
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type MavenAuthenticationTokenObservation struct {
}

type MavenAuthenticationTokenParameters struct {

	// Authentication Token generated through maven repository.
	// The Maven access token.
	// +kubebuilder:validation:Optional
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type MavenInitParameters struct {

	// A authentication_basic block as documented below.
	AuthenticationBasic []MavenAuthenticationBasicInitParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// A authentication_token block as documented below.
	AuthenticationToken []MavenAuthenticationTokenInitParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project. Changing this forces a new Service Connection Maven to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the server that matches the id element of the repository/mirror that Maven tries to connect to.
	// This is the ID of the server that matches the id element of the repository/mirror that Maven tries to connect to
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// The name of the service endpoint. Changing this forces a new Service Connection Maven to be created.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The URL of the Maven Repository.
	// Url for the Maven Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type MavenObservation struct {

	// A authentication_basic block as documented below.
	AuthenticationBasic []MavenAuthenticationBasicObservation `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// A authentication_token block as documented below.
	AuthenticationToken []MavenAuthenticationTokenParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project. Changing this forces a new Service Connection Maven to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the server that matches the id element of the repository/mirror that Maven tries to connect to.
	// This is the ID of the server that matches the id element of the repository/mirror that Maven tries to connect to
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// The name of the service endpoint. Changing this forces a new Service Connection Maven to be created.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The URL of the Maven Repository.
	// Url for the Maven Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type MavenParameters struct {

	// A authentication_basic block as documented below.
	// +kubebuilder:validation:Optional
	AuthenticationBasic []MavenAuthenticationBasicParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// A authentication_token block as documented below.
	// +kubebuilder:validation:Optional
	AuthenticationToken []MavenAuthenticationTokenParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project. Changing this forces a new Service Connection Maven to be created.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the server that matches the id element of the repository/mirror that Maven tries to connect to.
	// This is the ID of the server that matches the id element of the repository/mirror that Maven tries to connect to
	// +kubebuilder:validation:Optional
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// The name of the service endpoint. Changing this forces a new Service Connection Maven to be created.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The URL of the Maven Repository.
	// Url for the Maven Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// MavenSpec defines the desired state of Maven
type MavenSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MavenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MavenInitParameters `json:"initProvider,omitempty"`
}

// MavenStatus defines the observed state of Maven.
type MavenStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MavenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Maven is the Schema for the Mavens API. Manages a Service Connection for Maven.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type Maven struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repositoryId) || (has(self.initProvider) && has(self.initProvider.repositoryId))",message="spec.forProvider.repositoryId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   MavenSpec   `json:"spec"`
	Status MavenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MavenList contains a list of Mavens
type MavenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Maven `json:"items"`
}

// Repository type metadata.
var (
	Maven_Kind             = "Maven"
	Maven_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Maven_Kind}.String()
	Maven_KindAPIVersion   = Maven_Kind + "." + CRDGroupVersion.String()
	Maven_GroupVersionKind = CRDGroupVersion.WithKind(Maven_Kind)
)

func init() {
	SchemeBuilder.Register(&Maven{}, &MavenList{})
}
