apiVersion: branchpolicy.azuredevops.m.crossplane.io/v1alpha1
kind: PolicyBuildValidation
metadata:
  annotations:
    meta.upbound.io/example-id: branchpolicy/v1alpha1/policybuildvalidation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    blocking: true
    enabled: true
    projectId: ${azuredevops_project.example.id}
    settings:
    - buildDefinitionId: ${azuredevops_build_definition.example.id}
      displayName: Example build validation policy
      filenamePatterns:
      - /WebApp/*
      - '!/WebApp/Tests/*'
      - '*.cs'
      queueOnSourceUpdateOnly: true
      scope:
      - matchType: Exact
        repositoryId: ${azuredevops_git_repository.example.id}
        repositoryRef: ${azuredevops_git_repository.example.default_branch}
      - matchType: Prefix
        repositoryId: ${azuredevops_git_repository.example.id}
        repositoryRef: refs/heads/releases
      - matchType: DefaultBranch
      validDuration: 720

---

apiVersion: build.azuredevops.m.crossplane.io/v1alpha1
kind: Definition
metadata:
  annotations:
    meta.upbound.io/example-id: branchpolicy/v1alpha1/policybuildvalidation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    name: Example Build Definition
    projectId: ${azuredevops_project.example.id}
    repository:
    - repoId: ${azuredevops_git_repository.example.id}
      repoType: TfsGit
      ymlPath: azure-pipelines.yml

---

apiVersion: git.azuredevops.m.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: branchpolicy/v1alpha1/policybuildvalidation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Repository
    projectId: ${azuredevops_project.example.id}

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: branchpolicy/v1alpha1/policybuildvalidation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    name: Example Project
