apiVersion: serviceendpoint.azuredevops.m.crossplane.io/v1alpha1
kind: Incomingwebhook
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/incomingwebhook
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    description: Managed by Terraform
    httpHeader: X-Hub-Signature
    projectId: ${azuredevops_project.example.id}
    secretSecretRef:
      key: example-key
      name: example-secret
    serviceEndpointName: Example IncomingWebhook
    webhookName: example_webhook

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/incomingwebhook
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
