apiVersion: serviceendpoint.azuredevops.crossplane.io/v1alpha1
kind: GenericGit
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/genericgit
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    projectId: ${azuredevops_project.example.id}
    repositoryUrl: https://dev.azure.com/org/project/_git/repository
    serviceEndpointName: Example Generic Git
    username: username

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/genericgit
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
