apiVersion: serviceendpoint.azuredevops.crossplane.io/v1alpha1
kind: Jenkins
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/jenkins
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    acceptUntrustedCerts: false
    description: Service Endpoint for 'Jenkins' (Managed by Terraform)
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    projectId: ${azuredevops_project.example.id}
    serviceEndpointName: jenkins-example
    url: https://example.com
    username: username

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/jenkins
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
