apiVersion: serviceendpoint.azuredevops.crossplane.io/v1alpha1
kind: Kubernetes
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/kubernetes
  labels:
    testing.upbound.io/example-name: example-azure
  name: example-azure
spec:
  forProvider:
    apiserverUrl: https://sample-kubernetes-cluster.hcp.westeurope.azmk8s.io
    authorizationType: AzureSubscription
    azureSubscription:
    - clusterName: example-aks
      namespace: default
      resourcegroupId: example-rg
      subscriptionId: 00000000-0000-0000-0000-000000000000
      subscriptionName: Example
      tenantId: 00000000-0000-0000-0000-000000000000
    projectId: ${azuredevops_project.example.id}
    serviceEndpointName: Example Kubernetes

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/kubernetes
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
