// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ApprovalInitParameters struct {

	// Specifies a list of approver IDs.
	Approvers []*string `json:"approvers,omitempty" tf:"approvers,omitempty"`

	// The instructions for the approvers.
	Instructions *string `json:"instructions,omitempty" tf:"instructions,omitempty"`

	// The minimum number of approvers. This property is applicable when there is more than 1 approver.
	MinimumRequiredApprovers *float64 `json:"minimumRequiredApprovers,omitempty" tf:"minimum_required_approvers,omitempty"`

	// The project ID. Changing this forces a new Approval Check to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Can the requestor approve? Defaults to false.
	RequesterCanApprove *bool `json:"requesterCanApprove,omitempty" tf:"requester_can_approve,omitempty"`

	// The ID of the resource being protected by the check. Changing this forces a new Approval Check to be created.
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup. Changing this forces a new Approval Check to be created.
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// The timeout in minutes for the approval.  Defaults to 43200.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type ApprovalObservation struct {

	// Specifies a list of approver IDs.
	Approvers []*string `json:"approvers,omitempty" tf:"approvers,omitempty"`

	// The ID of the check.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The instructions for the approvers.
	Instructions *string `json:"instructions,omitempty" tf:"instructions,omitempty"`

	// The minimum number of approvers. This property is applicable when there is more than 1 approver.
	MinimumRequiredApprovers *float64 `json:"minimumRequiredApprovers,omitempty" tf:"minimum_required_approvers,omitempty"`

	// The project ID. Changing this forces a new Approval Check to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Can the requestor approve? Defaults to false.
	RequesterCanApprove *bool `json:"requesterCanApprove,omitempty" tf:"requester_can_approve,omitempty"`

	// The ID of the resource being protected by the check. Changing this forces a new Approval Check to be created.
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup. Changing this forces a new Approval Check to be created.
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// The timeout in minutes for the approval.  Defaults to 43200.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// The version of the check.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type ApprovalParameters struct {

	// Specifies a list of approver IDs.
	// +kubebuilder:validation:Optional
	Approvers []*string `json:"approvers,omitempty" tf:"approvers,omitempty"`

	// The instructions for the approvers.
	// +kubebuilder:validation:Optional
	Instructions *string `json:"instructions,omitempty" tf:"instructions,omitempty"`

	// The minimum number of approvers. This property is applicable when there is more than 1 approver.
	// +kubebuilder:validation:Optional
	MinimumRequiredApprovers *float64 `json:"minimumRequiredApprovers,omitempty" tf:"minimum_required_approvers,omitempty"`

	// The project ID. Changing this forces a new Approval Check to be created.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Can the requestor approve? Defaults to false.
	// +kubebuilder:validation:Optional
	RequesterCanApprove *bool `json:"requesterCanApprove,omitempty" tf:"requester_can_approve,omitempty"`

	// The ID of the resource being protected by the check. Changing this forces a new Approval Check to be created.
	// +kubebuilder:validation:Optional
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup. Changing this forces a new Approval Check to be created.
	// +kubebuilder:validation:Optional
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// The timeout in minutes for the approval.  Defaults to 43200.
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

// ApprovalSpec defines the desired state of Approval
type ApprovalSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ApprovalParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApprovalInitParameters `json:"initProvider,omitempty"`
}

// ApprovalStatus defines the observed state of Approval.
type ApprovalStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ApprovalObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Approval is the Schema for the Approvals API. Manages an Approval Check.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type Approval struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.approvers) || (has(self.initProvider) && has(self.initProvider.approvers))",message="spec.forProvider.approvers is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetResourceId) || (has(self.initProvider) && has(self.initProvider.targetResourceId))",message="spec.forProvider.targetResourceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetResourceType) || (has(self.initProvider) && has(self.initProvider.targetResourceType))",message="spec.forProvider.targetResourceType is a required parameter"
	Spec   ApprovalSpec   `json:"spec"`
	Status ApprovalStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApprovalList contains a list of Approvals
type ApprovalList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Approval `json:"items"`
}

// Repository type metadata.
var (
	Approval_Kind             = "Approval"
	Approval_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Approval_Kind}.String()
	Approval_KindAPIVersion   = Approval_Kind + "." + CRDGroupVersion.String()
	Approval_GroupVersionKind = CRDGroupVersion.WithKind(Approval_Kind)
)

func init() {
	SchemeBuilder.Register(&Approval{}, &ApprovalList{})
}
