// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type RequiredTemplateInitParameters struct {

	// The project ID. Changing this forces a new Required Template Check to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// One or more required_template blocks documented below.
	RequiredTemplate []RequiredTemplateRequiredTemplateInitParameters `json:"requiredTemplate,omitempty" tf:"required_template,omitempty"`

	// The ID of the resource being protected by the check. Changing this forces a new Required Template Check to be created.
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup. Changing this forces a new Required Template Check to be created.
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`
}

type RequiredTemplateObservation struct {

	// The ID of the check.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The project ID. Changing this forces a new Required Template Check to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// One or more required_template blocks documented below.
	RequiredTemplate []RequiredTemplateRequiredTemplateObservation `json:"requiredTemplate,omitempty" tf:"required_template,omitempty"`

	// The ID of the resource being protected by the check. Changing this forces a new Required Template Check to be created.
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup. Changing this forces a new Required Template Check to be created.
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// The version of the check.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type RequiredTemplateParameters struct {

	// The project ID. Changing this forces a new Required Template Check to be created.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// One or more required_template blocks documented below.
	// +kubebuilder:validation:Optional
	RequiredTemplate []RequiredTemplateRequiredTemplateParameters `json:"requiredTemplate,omitempty" tf:"required_template,omitempty"`

	// The ID of the resource being protected by the check. Changing this forces a new Required Template Check to be created.
	// +kubebuilder:validation:Optional
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup. Changing this forces a new Required Template Check to be created.
	// +kubebuilder:validation:Optional
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`
}

type RequiredTemplateRequiredTemplateInitParameters struct {

	// The name of the repository storing the template.
	RepositoryName *string `json:"repositoryName,omitempty" tf:"repository_name,omitempty"`

	// The branch in which the template will be referenced.
	RepositoryRef *string `json:"repositoryRef,omitempty" tf:"repository_ref,omitempty"`

	// The type of the repository storing the template. Valid values: azuregit, github, githubenterprise, bitbucket. Defaults to azuregit.
	RepositoryType *string `json:"repositoryType,omitempty" tf:"repository_type,omitempty"`

	// The path to the template yaml.
	TemplatePath *string `json:"templatePath,omitempty" tf:"template_path,omitempty"`
}

type RequiredTemplateRequiredTemplateObservation struct {

	// The name of the repository storing the template.
	RepositoryName *string `json:"repositoryName,omitempty" tf:"repository_name,omitempty"`

	// The branch in which the template will be referenced.
	RepositoryRef *string `json:"repositoryRef,omitempty" tf:"repository_ref,omitempty"`

	// The type of the repository storing the template. Valid values: azuregit, github, githubenterprise, bitbucket. Defaults to azuregit.
	RepositoryType *string `json:"repositoryType,omitempty" tf:"repository_type,omitempty"`

	// The path to the template yaml.
	TemplatePath *string `json:"templatePath,omitempty" tf:"template_path,omitempty"`
}

type RequiredTemplateRequiredTemplateParameters struct {

	// The name of the repository storing the template.
	// +kubebuilder:validation:Optional
	RepositoryName *string `json:"repositoryName" tf:"repository_name,omitempty"`

	// The branch in which the template will be referenced.
	// +kubebuilder:validation:Optional
	RepositoryRef *string `json:"repositoryRef" tf:"repository_ref,omitempty"`

	// The type of the repository storing the template. Valid values: azuregit, github, githubenterprise, bitbucket. Defaults to azuregit.
	// +kubebuilder:validation:Optional
	RepositoryType *string `json:"repositoryType,omitempty" tf:"repository_type,omitempty"`

	// The path to the template yaml.
	// +kubebuilder:validation:Optional
	TemplatePath *string `json:"templatePath" tf:"template_path,omitempty"`
}

// RequiredTemplateSpec defines the desired state of RequiredTemplate
type RequiredTemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RequiredTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RequiredTemplateInitParameters `json:"initProvider,omitempty"`
}

// RequiredTemplateStatus defines the observed state of RequiredTemplate.
type RequiredTemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RequiredTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RequiredTemplate is the Schema for the RequiredTemplates API. Manages a Required Template Check.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type RequiredTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.requiredTemplate) || (has(self.initProvider) && has(self.initProvider.requiredTemplate))",message="spec.forProvider.requiredTemplate is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetResourceId) || (has(self.initProvider) && has(self.initProvider.targetResourceId))",message="spec.forProvider.targetResourceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetResourceType) || (has(self.initProvider) && has(self.initProvider.targetResourceType))",message="spec.forProvider.targetResourceType is a required parameter"
	Spec   RequiredTemplateSpec   `json:"spec"`
	Status RequiredTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RequiredTemplateList contains a list of RequiredTemplates
type RequiredTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RequiredTemplate `json:"items"`
}

// Repository type metadata.
var (
	RequiredTemplate_Kind             = "RequiredTemplate"
	RequiredTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RequiredTemplate_Kind}.String()
	RequiredTemplate_KindAPIVersion   = RequiredTemplate_Kind + "." + CRDGroupVersion.String()
	RequiredTemplate_GroupVersionKind = CRDGroupVersion.WithKind(RequiredTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&RequiredTemplate{}, &RequiredTemplateList{})
}
