// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PolicyStatusCheckInitParameters struct {

	// A flag indicating if the policy should be blocking. Defaults to true.
	Blocking *bool `json:"blocking,omitempty" tf:"blocking,omitempty"`

	// A flag indicating if the policy should be enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the project in which the policy will be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Configuration for the policy. This block must be defined exactly once.
	Settings []PolicyStatusCheckSettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`
}

type PolicyStatusCheckObservation struct {

	// A flag indicating if the policy should be blocking. Defaults to true.
	Blocking *bool `json:"blocking,omitempty" tf:"blocking,omitempty"`

	// A flag indicating if the policy should be enabled. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of branch policy configuration.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project in which the policy will be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Configuration for the policy. This block must be defined exactly once.
	Settings []PolicyStatusCheckSettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`
}

type PolicyStatusCheckParameters struct {

	// A flag indicating if the policy should be blocking. Defaults to true.
	// +kubebuilder:validation:Optional
	Blocking *bool `json:"blocking,omitempty" tf:"blocking,omitempty"`

	// A flag indicating if the policy should be enabled. Defaults to true.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the project in which the policy will be created.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Configuration for the policy. This block must be defined exactly once.
	// +kubebuilder:validation:Optional
	Settings []PolicyStatusCheckSettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`
}

type PolicyStatusCheckSettingsInitParameters struct {

	// Policy applicability. If policy applicability is default, apply unless "Not Applicable"
	// status is posted to the pull request. If policy applicability is conditional, policy is applied only after a status
	// is posted to the pull request.
	Applicability *string `json:"applicability,omitempty" tf:"applicability,omitempty"`

	// The authorized user can post the status.
	AuthorID *string `json:"authorId,omitempty" tf:"author_id,omitempty"`

	// The display name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// If a path filter is set, the policy will only apply when files which match the filter are changes. Not setting this field means that the policy will always apply. You can specify absolute paths and wildcards. Example: ["/WebApp/Models/Data.cs", "/WebApp/*", "*.cs"]. Paths prefixed with "!" are excluded. Example: ["/WebApp/*", "!/WebApp/Tests/*"]. Order is significant.
	FilenamePatterns []*string `json:"filenamePatterns,omitempty" tf:"filename_patterns,omitempty"`

	// The genre of the status to check (see Microsoft Documentation)
	Genre *string `json:"genre,omitempty" tf:"genre,omitempty"`

	// Reset status whenever there are new changes.
	InvalidateOnUpdate *bool `json:"invalidateOnUpdate,omitempty" tf:"invalidate_on_update,omitempty"`

	// The status name to check.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Controls which repositories and branches the policy will be enabled for. This block must be defined
	// at least once.
	Scope []PolicyStatusCheckSettingsScopeInitParameters `json:"scope,omitempty" tf:"scope,omitempty"`
}

type PolicyStatusCheckSettingsObservation struct {

	// Policy applicability. If policy applicability is default, apply unless "Not Applicable"
	// status is posted to the pull request. If policy applicability is conditional, policy is applied only after a status
	// is posted to the pull request.
	Applicability *string `json:"applicability,omitempty" tf:"applicability,omitempty"`

	// The authorized user can post the status.
	AuthorID *string `json:"authorId,omitempty" tf:"author_id,omitempty"`

	// The display name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// If a path filter is set, the policy will only apply when files which match the filter are changes. Not setting this field means that the policy will always apply. You can specify absolute paths and wildcards. Example: ["/WebApp/Models/Data.cs", "/WebApp/*", "*.cs"]. Paths prefixed with "!" are excluded. Example: ["/WebApp/*", "!/WebApp/Tests/*"]. Order is significant.
	FilenamePatterns []*string `json:"filenamePatterns,omitempty" tf:"filename_patterns,omitempty"`

	// The genre of the status to check (see Microsoft Documentation)
	Genre *string `json:"genre,omitempty" tf:"genre,omitempty"`

	// Reset status whenever there are new changes.
	InvalidateOnUpdate *bool `json:"invalidateOnUpdate,omitempty" tf:"invalidate_on_update,omitempty"`

	// The status name to check.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Controls which repositories and branches the policy will be enabled for. This block must be defined
	// at least once.
	Scope []PolicyStatusCheckSettingsScopeObservation `json:"scope,omitempty" tf:"scope,omitempty"`
}

type PolicyStatusCheckSettingsParameters struct {

	// Policy applicability. If policy applicability is default, apply unless "Not Applicable"
	// status is posted to the pull request. If policy applicability is conditional, policy is applied only after a status
	// is posted to the pull request.
	// +kubebuilder:validation:Optional
	Applicability *string `json:"applicability,omitempty" tf:"applicability,omitempty"`

	// The authorized user can post the status.
	// +kubebuilder:validation:Optional
	AuthorID *string `json:"authorId,omitempty" tf:"author_id,omitempty"`

	// The display name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// If a path filter is set, the policy will only apply when files which match the filter are changes. Not setting this field means that the policy will always apply. You can specify absolute paths and wildcards. Example: ["/WebApp/Models/Data.cs", "/WebApp/*", "*.cs"]. Paths prefixed with "!" are excluded. Example: ["/WebApp/*", "!/WebApp/Tests/*"]. Order is significant.
	// +kubebuilder:validation:Optional
	FilenamePatterns []*string `json:"filenamePatterns,omitempty" tf:"filename_patterns,omitempty"`

	// The genre of the status to check (see Microsoft Documentation)
	// +kubebuilder:validation:Optional
	Genre *string `json:"genre,omitempty" tf:"genre,omitempty"`

	// Reset status whenever there are new changes.
	// +kubebuilder:validation:Optional
	InvalidateOnUpdate *bool `json:"invalidateOnUpdate,omitempty" tf:"invalidate_on_update,omitempty"`

	// The status name to check.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Controls which repositories and branches the policy will be enabled for. This block must be defined
	// at least once.
	// +kubebuilder:validation:Optional
	Scope []PolicyStatusCheckSettingsScopeParameters `json:"scope" tf:"scope,omitempty"`
}

type PolicyStatusCheckSettingsScopeInitParameters struct {

	// The match type to use when applying the policy. Supported values are Exact (default), Prefix or DefaultBranch.
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// The repository ID. Needed only if the scope of the policy will be limited to a single repository. If match_type is DefaultBranch, this should not be defined.
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// The ref pattern to use for the match when match_type other than DefaultBranch. If match_type is Exact, this should be a qualified ref such as refs/heads/master. If match_type is Prefix, this should be a ref path such as refs/heads/releases.
	RepositoryRef *string `json:"repositoryRef,omitempty" tf:"repository_ref,omitempty"`
}

type PolicyStatusCheckSettingsScopeObservation struct {

	// The match type to use when applying the policy. Supported values are Exact (default), Prefix or DefaultBranch.
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// The repository ID. Needed only if the scope of the policy will be limited to a single repository. If match_type is DefaultBranch, this should not be defined.
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// The ref pattern to use for the match when match_type other than DefaultBranch. If match_type is Exact, this should be a qualified ref such as refs/heads/master. If match_type is Prefix, this should be a ref path such as refs/heads/releases.
	RepositoryRef *string `json:"repositoryRef,omitempty" tf:"repository_ref,omitempty"`
}

type PolicyStatusCheckSettingsScopeParameters struct {

	// The match type to use when applying the policy. Supported values are Exact (default), Prefix or DefaultBranch.
	// +kubebuilder:validation:Optional
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// The repository ID. Needed only if the scope of the policy will be limited to a single repository. If match_type is DefaultBranch, this should not be defined.
	// +kubebuilder:validation:Optional
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// The ref pattern to use for the match when match_type other than DefaultBranch. If match_type is Exact, this should be a qualified ref such as refs/heads/master. If match_type is Prefix, this should be a ref path such as refs/heads/releases.
	// +kubebuilder:validation:Optional
	RepositoryRef *string `json:"repositoryRef,omitempty" tf:"repository_ref,omitempty"`
}

// PolicyStatusCheckSpec defines the desired state of PolicyStatusCheck
type PolicyStatusCheckSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyStatusCheckParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyStatusCheckInitParameters `json:"initProvider,omitempty"`
}

// PolicyStatusCheckStatus defines the observed state of PolicyStatusCheck.
type PolicyStatusCheckStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyStatusCheckObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyStatusCheck is the Schema for the PolicyStatusChecks API. Manages status check branch policy within Azure DevOps project.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type PolicyStatusCheck struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settings) || (has(self.initProvider) && has(self.initProvider.settings))",message="spec.forProvider.settings is a required parameter"
	Spec   PolicyStatusCheckSpec   `json:"spec"`
	Status PolicyStatusCheckStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyStatusCheckList contains a list of PolicyStatusChecks
type PolicyStatusCheckList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyStatusCheck `json:"items"`
}

// Repository type metadata.
var (
	PolicyStatusCheck_Kind             = "PolicyStatusCheck"
	PolicyStatusCheck_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyStatusCheck_Kind}.String()
	PolicyStatusCheck_KindAPIVersion   = PolicyStatusCheck_Kind + "." + CRDGroupVersion.String()
	PolicyStatusCheck_GroupVersionKind = CRDGroupVersion.WithKind(PolicyStatusCheck_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyStatusCheck{}, &PolicyStatusCheckList{})
}
