apiVersion: git.azuredevops.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    defaultBranch: refs/heads/main
    initialization:
    - initType: Clean
    name: Example Git Repository
    projectId: ${azuredevops_project.example.id}

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
