// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BusinessHoursInitParameters struct {

	// The name of the business hours check displayed in the web UI.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The end of the time period that this check will be allowed to pass, specified as 24-hour time with leading zeros.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// This check will pass on Fridays. Defaults to false.
	Friday *bool `json:"friday,omitempty" tf:"friday,omitempty"`

	// This check will pass on Mondays. Defaults to false.
	Monday *bool `json:"monday,omitempty" tf:"monday,omitempty"`

	// The project ID.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// This check will pass on Saturdays. Defaults to false.
	Saturday *bool `json:"saturday,omitempty" tf:"saturday,omitempty"`

	// The beginning of the time period that this check will be allowed to pass, specified as 24-hour time with leading zeros.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// This check will pass on Sundays. Defaults to false.
	Sunday *bool `json:"sunday,omitempty" tf:"sunday,omitempty"`

	// The ID of the resource being protected by the check.
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup.
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// This check will pass on Thursdays. Defaults to false.
	Thursday *bool `json:"thursday,omitempty" tf:"thursday,omitempty"`

	// The time zone this check will be evaluated in. See below for supported values.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// The timeout in minutes for the business hours check. Defaults to 1440.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// This check will pass on Tuesday. Defaults to false.
	Tuesday *bool `json:"tuesday,omitempty" tf:"tuesday,omitempty"`

	// This check will pass on Wednesdays. Defaults to false.
	Wednesday *bool `json:"wednesday,omitempty" tf:"wednesday,omitempty"`
}

type BusinessHoursObservation struct {

	// The name of the business hours check displayed in the web UI.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The end of the time period that this check will be allowed to pass, specified as 24-hour time with leading zeros.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// This check will pass on Fridays. Defaults to false.
	Friday *bool `json:"friday,omitempty" tf:"friday,omitempty"`

	// The ID of the check.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// This check will pass on Mondays. Defaults to false.
	Monday *bool `json:"monday,omitempty" tf:"monday,omitempty"`

	// The project ID.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// This check will pass on Saturdays. Defaults to false.
	Saturday *bool `json:"saturday,omitempty" tf:"saturday,omitempty"`

	// The beginning of the time period that this check will be allowed to pass, specified as 24-hour time with leading zeros.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// This check will pass on Sundays. Defaults to false.
	Sunday *bool `json:"sunday,omitempty" tf:"sunday,omitempty"`

	// The ID of the resource being protected by the check.
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup.
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// This check will pass on Thursdays. Defaults to false.
	Thursday *bool `json:"thursday,omitempty" tf:"thursday,omitempty"`

	// The time zone this check will be evaluated in. See below for supported values.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// The timeout in minutes for the business hours check. Defaults to 1440.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// This check will pass on Tuesday. Defaults to false.
	Tuesday *bool `json:"tuesday,omitempty" tf:"tuesday,omitempty"`

	// The version of the check.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`

	// This check will pass on Wednesdays. Defaults to false.
	Wednesday *bool `json:"wednesday,omitempty" tf:"wednesday,omitempty"`
}

type BusinessHoursParameters struct {

	// The name of the business hours check displayed in the web UI.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The end of the time period that this check will be allowed to pass, specified as 24-hour time with leading zeros.
	// +kubebuilder:validation:Optional
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// This check will pass on Fridays. Defaults to false.
	// +kubebuilder:validation:Optional
	Friday *bool `json:"friday,omitempty" tf:"friday,omitempty"`

	// This check will pass on Mondays. Defaults to false.
	// +kubebuilder:validation:Optional
	Monday *bool `json:"monday,omitempty" tf:"monday,omitempty"`

	// The project ID.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// This check will pass on Saturdays. Defaults to false.
	// +kubebuilder:validation:Optional
	Saturday *bool `json:"saturday,omitempty" tf:"saturday,omitempty"`

	// The beginning of the time period that this check will be allowed to pass, specified as 24-hour time with leading zeros.
	// +kubebuilder:validation:Optional
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// This check will pass on Sundays. Defaults to false.
	// +kubebuilder:validation:Optional
	Sunday *bool `json:"sunday,omitempty" tf:"sunday,omitempty"`

	// The ID of the resource being protected by the check.
	// +kubebuilder:validation:Optional
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup.
	// +kubebuilder:validation:Optional
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// This check will pass on Thursdays. Defaults to false.
	// +kubebuilder:validation:Optional
	Thursday *bool `json:"thursday,omitempty" tf:"thursday,omitempty"`

	// The time zone this check will be evaluated in. See below for supported values.
	// +kubebuilder:validation:Optional
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// The timeout in minutes for the business hours check. Defaults to 1440.
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// This check will pass on Tuesday. Defaults to false.
	// +kubebuilder:validation:Optional
	Tuesday *bool `json:"tuesday,omitempty" tf:"tuesday,omitempty"`

	// This check will pass on Wednesdays. Defaults to false.
	// +kubebuilder:validation:Optional
	Wednesday *bool `json:"wednesday,omitempty" tf:"wednesday,omitempty"`
}

// BusinessHoursSpec defines the desired state of BusinessHours
type BusinessHoursSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BusinessHoursParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BusinessHoursInitParameters `json:"initProvider,omitempty"`
}

// BusinessHoursStatus defines the observed state of BusinessHours.
type BusinessHoursStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BusinessHoursObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BusinessHours is the Schema for the BusinessHourss API. Manages a business hours check.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type BusinessHours struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endTime) || (has(self.initProvider) && has(self.initProvider.endTime))",message="spec.forProvider.endTime is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startTime) || (has(self.initProvider) && has(self.initProvider.startTime))",message="spec.forProvider.startTime is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetResourceId) || (has(self.initProvider) && has(self.initProvider.targetResourceId))",message="spec.forProvider.targetResourceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetResourceType) || (has(self.initProvider) && has(self.initProvider.targetResourceType))",message="spec.forProvider.targetResourceType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.timeZone) || (has(self.initProvider) && has(self.initProvider.timeZone))",message="spec.forProvider.timeZone is a required parameter"
	Spec   BusinessHoursSpec   `json:"spec"`
	Status BusinessHoursStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BusinessHoursList contains a list of BusinessHourss
type BusinessHoursList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BusinessHours `json:"items"`
}

// Repository type metadata.
var (
	BusinessHours_Kind             = "BusinessHours"
	BusinessHours_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BusinessHours_Kind}.String()
	BusinessHours_KindAPIVersion   = BusinessHours_Kind + "." + CRDGroupVersion.String()
	BusinessHours_GroupVersionKind = CRDGroupVersion.WithKind(BusinessHours_Kind)
)

func init() {
	SchemeBuilder.Register(&BusinessHours{}, &BusinessHoursList{})
}
