// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ExclusiveLockInitParameters struct {

	// The project ID. Changing this forces a new Exclusive Lock Check to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the resource being protected by the check. Changing this forces a new Exclusive Lock to be created.
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup. Changing this forces a new Exclusive Lock to be created.
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// The timeout in minutes for the exclusive lock. Defaults to 43200.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type ExclusiveLockObservation struct {

	// The ID of the check.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The project ID. Changing this forces a new Exclusive Lock Check to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the resource being protected by the check. Changing this forces a new Exclusive Lock to be created.
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup. Changing this forces a new Exclusive Lock to be created.
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// The timeout in minutes for the exclusive lock. Defaults to 43200.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// The version of the check.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type ExclusiveLockParameters struct {

	// The project ID. Changing this forces a new Exclusive Lock Check to be created.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the resource being protected by the check. Changing this forces a new Exclusive Lock to be created.
	// +kubebuilder:validation:Optional
	TargetResourceID *string `json:"targetResourceId,omitempty" tf:"target_resource_id,omitempty"`

	// The type of resource being protected by the check. Valid values: endpoint, environment, queue, repository, securefile, variablegroup. Changing this forces a new Exclusive Lock to be created.
	// +kubebuilder:validation:Optional
	TargetResourceType *string `json:"targetResourceType,omitempty" tf:"target_resource_type,omitempty"`

	// The timeout in minutes for the exclusive lock. Defaults to 43200.
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

// ExclusiveLockSpec defines the desired state of ExclusiveLock
type ExclusiveLockSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ExclusiveLockParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ExclusiveLockInitParameters `json:"initProvider,omitempty"`
}

// ExclusiveLockStatus defines the observed state of ExclusiveLock.
type ExclusiveLockStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ExclusiveLockObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ExclusiveLock is the Schema for the ExclusiveLocks API. Manages an Exclusive Lock Check.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type ExclusiveLock struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetResourceId) || (has(self.initProvider) && has(self.initProvider.targetResourceId))",message="spec.forProvider.targetResourceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetResourceType) || (has(self.initProvider) && has(self.initProvider.targetResourceType))",message="spec.forProvider.targetResourceType is a required parameter"
	Spec   ExclusiveLockSpec   `json:"spec"`
	Status ExclusiveLockStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExclusiveLockList contains a list of ExclusiveLocks
type ExclusiveLockList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExclusiveLock `json:"items"`
}

// Repository type metadata.
var (
	ExclusiveLock_Kind             = "ExclusiveLock"
	ExclusiveLock_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ExclusiveLock_Kind}.String()
	ExclusiveLock_KindAPIVersion   = ExclusiveLock_Kind + "." + CRDGroupVersion.String()
	ExclusiveLock_GroupVersionKind = CRDGroupVersion.WithKind(ExclusiveLock_Kind)
)

func init() {
	SchemeBuilder.Register(&ExclusiveLock{}, &ExclusiveLockList{})
}
