// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AuthorizationInitParameters_2 struct {

	// Set to true to allow public access in the project. Type: boolean.
	// indicates whether the resource is authorized for use
	Authorized *bool `json:"authorized,omitempty" tf:"authorized,omitempty"`

	// The ID of the build definition to authorize. Type: string.
	// id of the build definition
	DefinitionID *float64 `json:"definitionId,omitempty" tf:"definition_id,omitempty"`

	// The project ID or project name. Type: string.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the resource to authorize. Type: string.
	// id of the resource
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// The type of the resource to authorize. Type: string. Valid values: endpoint, queue, variablegroup. Default value: endpoint.
	// type of the resource
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AuthorizationObservation_2 struct {

	// Set to true to allow public access in the project. Type: boolean.
	// indicates whether the resource is authorized for use
	Authorized *bool `json:"authorized,omitempty" tf:"authorized,omitempty"`

	// The ID of the build definition to authorize. Type: string.
	// id of the build definition
	DefinitionID *float64 `json:"definitionId,omitempty" tf:"definition_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The project ID or project name. Type: string.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the resource to authorize. Type: string.
	// id of the resource
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// The type of the resource to authorize. Type: string. Valid values: endpoint, queue, variablegroup. Default value: endpoint.
	// type of the resource
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AuthorizationParameters_2 struct {

	// Set to true to allow public access in the project. Type: boolean.
	// indicates whether the resource is authorized for use
	// +kubebuilder:validation:Optional
	Authorized *bool `json:"authorized,omitempty" tf:"authorized,omitempty"`

	// The ID of the build definition to authorize. Type: string.
	// id of the build definition
	// +kubebuilder:validation:Optional
	DefinitionID *float64 `json:"definitionId,omitempty" tf:"definition_id,omitempty"`

	// The project ID or project name. Type: string.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the resource to authorize. Type: string.
	// id of the resource
	// +kubebuilder:validation:Optional
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// The type of the resource to authorize. Type: string. Valid values: endpoint, queue, variablegroup. Default value: endpoint.
	// type of the resource
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// AuthorizationSpec defines the desired state of Authorization
type AuthorizationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AuthorizationParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuthorizationInitParameters_2 `json:"initProvider,omitempty"`
}

// AuthorizationStatus defines the observed state of Authorization.
type AuthorizationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthorizationObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Authorization is the Schema for the Authorizations API. Manages authorization of resources within Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type Authorization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authorized) || (has(self.initProvider) && has(self.initProvider.authorized))",message="spec.forProvider.authorized is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resourceId) || (has(self.initProvider) && has(self.initProvider.resourceId))",message="spec.forProvider.resourceId is a required parameter"
	Spec   AuthorizationSpec   `json:"spec"`
	Status AuthorizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthorizationList contains a list of Authorizations
type AuthorizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Authorization `json:"items"`
}

// Repository type metadata.
var (
	Authorization_Kind             = "Authorization"
	Authorization_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Authorization_Kind}.String()
	Authorization_KindAPIVersion   = Authorization_Kind + "." + CRDGroupVersion.String()
	Authorization_GroupVersionKind = CRDGroupVersion.WithKind(Authorization_Kind)
)

func init() {
	SchemeBuilder.Register(&Authorization{}, &AuthorizationList{})
}
