// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AwsInitParameters struct {

	// The AWS access key ID for signing programmatic requests.
	// The AWS access key ID for signing programmatic requests.
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Optional identifier for the assumed role session.
	// Optional identifier for the assumed role session.
	RoleSessionName *string `json:"roleSessionName,omitempty" tf:"role_session_name,omitempty"`

	// The Amazon Resource Name (ARN) of the role to assume.
	// The Amazon Resource Name (ARN) of the role to assume.
	RoleToAssume *string `json:"roleToAssume,omitempty" tf:"role_to_assume,omitempty"`

	// The AWS secret access key for signing programmatic requests.
	// The AWS secret access key for signing programmatic requests.
	SecretAccessKeySecretRef v1.SecretKeySelector `json:"secretAccessKeySecretRef" tf:"-"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The AWS session token for signing programmatic requests.
	// The AWS session token for signing programmatic requests.
	SessionTokenSecretRef *v1.SecretKeySelector `json:"sessionTokenSecretRef,omitempty" tf:"-"`
}

type AwsObservation struct {

	// The AWS access key ID for signing programmatic requests.
	// The AWS access key ID for signing programmatic requests.
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Optional identifier for the assumed role session.
	// Optional identifier for the assumed role session.
	RoleSessionName *string `json:"roleSessionName,omitempty" tf:"role_session_name,omitempty"`

	// The Amazon Resource Name (ARN) of the role to assume.
	// The Amazon Resource Name (ARN) of the role to assume.
	RoleToAssume *string `json:"roleToAssume,omitempty" tf:"role_to_assume,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

type AwsParameters struct {

	// The AWS access key ID for signing programmatic requests.
	// The AWS access key ID for signing programmatic requests.
	// +kubebuilder:validation:Optional
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	// +kubebuilder:validation:Optional
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// The ID of the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Optional identifier for the assumed role session.
	// Optional identifier for the assumed role session.
	// +kubebuilder:validation:Optional
	RoleSessionName *string `json:"roleSessionName,omitempty" tf:"role_session_name,omitempty"`

	// The Amazon Resource Name (ARN) of the role to assume.
	// The Amazon Resource Name (ARN) of the role to assume.
	// +kubebuilder:validation:Optional
	RoleToAssume *string `json:"roleToAssume,omitempty" tf:"role_to_assume,omitempty"`

	// The AWS secret access key for signing programmatic requests.
	// The AWS secret access key for signing programmatic requests.
	// +kubebuilder:validation:Optional
	SecretAccessKeySecretRef v1.SecretKeySelector `json:"secretAccessKeySecretRef" tf:"-"`

	// The Service Endpoint name.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The AWS session token for signing programmatic requests.
	// The AWS session token for signing programmatic requests.
	// +kubebuilder:validation:Optional
	SessionTokenSecretRef *v1.SecretKeySelector `json:"sessionTokenSecretRef,omitempty" tf:"-"`
}

// AwsSpec defines the desired state of Aws
type AwsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AwsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AwsInitParameters `json:"initProvider,omitempty"`
}

// AwsStatus defines the observed state of Aws.
type AwsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AwsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Aws is the Schema for the Awss API. Manages a AWS service endpoint within Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type Aws struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accessKeyId) || (has(self.initProvider) && has(self.initProvider.accessKeyId))",message="spec.forProvider.accessKeyId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretAccessKeySecretRef)",message="spec.forProvider.secretAccessKeySecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	Spec   AwsSpec   `json:"spec"`
	Status AwsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AwsList contains a list of Awss
type AwsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Aws `json:"items"`
}

// Repository type metadata.
var (
	Aws_Kind             = "Aws"
	Aws_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Aws_Kind}.String()
	Aws_KindAPIVersion   = Aws_Kind + "." + CRDGroupVersion.String()
	Aws_GroupVersionKind = CRDGroupVersion.WithKind(Aws_Kind)
)

func init() {
	SchemeBuilder.Register(&Aws{}, &AwsList{})
}
