// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DockerregistryInitParameters struct {

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The email for Docker account user.
	// The DockerRegistry email address which should be used.
	DockerEmail *string `json:"dockerEmail,omitempty" tf:"docker_email,omitempty"`

	// The password for the account user identified above.
	// The DockerRegistry password which should be used.
	DockerPasswordSecretRef *v1.SecretKeySelector `json:"dockerPasswordSecretRef,omitempty" tf:"-"`

	// The URL of the Docker registry. (Default: "https://index.docker.io/v1/")
	// The DockerRegistry registry which should be used.
	DockerRegistry *string `json:"dockerRegistry,omitempty" tf:"docker_registry,omitempty"`

	// The identifier of the Docker account user.
	// The DockerRegistry username which should be used.
	DockerUsername *string `json:"dockerUsername,omitempty" tf:"docker_username,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Can be "DockerHub" or "Others" (Default "DockerHub")
	RegistryType *string `json:"registryType,omitempty" tf:"registry_type,omitempty"`

	// The name you will use to refer to this service connection in task inputs.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

type DockerregistryObservation struct {

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The email for Docker account user.
	// The DockerRegistry email address which should be used.
	DockerEmail *string `json:"dockerEmail,omitempty" tf:"docker_email,omitempty"`

	// The URL of the Docker registry. (Default: "https://index.docker.io/v1/")
	// The DockerRegistry registry which should be used.
	DockerRegistry *string `json:"dockerRegistry,omitempty" tf:"docker_registry,omitempty"`

	// The identifier of the Docker account user.
	// The DockerRegistry username which should be used.
	DockerUsername *string `json:"dockerUsername,omitempty" tf:"docker_username,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Can be "DockerHub" or "Others" (Default "DockerHub")
	RegistryType *string `json:"registryType,omitempty" tf:"registry_type,omitempty"`

	// The name you will use to refer to this service connection in task inputs.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

type DockerregistryParameters struct {

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The email for Docker account user.
	// The DockerRegistry email address which should be used.
	// +kubebuilder:validation:Optional
	DockerEmail *string `json:"dockerEmail,omitempty" tf:"docker_email,omitempty"`

	// The password for the account user identified above.
	// The DockerRegistry password which should be used.
	// +kubebuilder:validation:Optional
	DockerPasswordSecretRef *v1.SecretKeySelector `json:"dockerPasswordSecretRef,omitempty" tf:"-"`

	// The URL of the Docker registry. (Default: "https://index.docker.io/v1/")
	// The DockerRegistry registry which should be used.
	// +kubebuilder:validation:Optional
	DockerRegistry *string `json:"dockerRegistry,omitempty" tf:"docker_registry,omitempty"`

	// The identifier of the Docker account user.
	// The DockerRegistry username which should be used.
	// +kubebuilder:validation:Optional
	DockerUsername *string `json:"dockerUsername,omitempty" tf:"docker_username,omitempty"`

	// The ID of the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Can be "DockerHub" or "Others" (Default "DockerHub")
	// +kubebuilder:validation:Optional
	RegistryType *string `json:"registryType,omitempty" tf:"registry_type,omitempty"`

	// The name you will use to refer to this service connection in task inputs.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

// DockerregistrySpec defines the desired state of Dockerregistry
type DockerregistrySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DockerregistryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DockerregistryInitParameters `json:"initProvider,omitempty"`
}

// DockerregistryStatus defines the observed state of Dockerregistry.
type DockerregistryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DockerregistryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Dockerregistry is the Schema for the Dockerregistrys API. Manages a Docker Registry service endpoint within Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type Dockerregistry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	Spec   DockerregistrySpec   `json:"spec"`
	Status DockerregistryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DockerregistryList contains a list of Dockerregistrys
type DockerregistryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Dockerregistry `json:"items"`
}

// Repository type metadata.
var (
	Dockerregistry_Kind             = "Dockerregistry"
	Dockerregistry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Dockerregistry_Kind}.String()
	Dockerregistry_KindAPIVersion   = Dockerregistry_Kind + "." + CRDGroupVersion.String()
	Dockerregistry_GroupVersionKind = CRDGroupVersion.WithKind(Dockerregistry_Kind)
)

func init() {
	SchemeBuilder.Register(&Dockerregistry{}, &DockerregistryList{})
}
