// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IncomingwebhookInitParameters struct {

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Http header name on which checksum will be sent.
	// Optional http header name on which checksum will be sent.
	HTTPHeader *string `json:"httpHeader,omitempty" tf:"http_header,omitempty"`

	// The ID of the project. Changing this forces a new Service Connection Incoming WebHook to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Secret for the WebHook. WebHook service will use this secret to calculate the payload checksum.
	// Optional secret for the webhook. WebHook service will use this secret to calculate the payload checksum.
	SecretSecretRef *v1.SecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// The name of the service endpoint. Changing this forces a new Service Connection Incoming WebHook to be created.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The name of the WebHook.
	// The name of the WebHook.
	WebhookName *string `json:"webhookName,omitempty" tf:"webhook_name,omitempty"`
}

type IncomingwebhookObservation struct {

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Http header name on which checksum will be sent.
	// Optional http header name on which checksum will be sent.
	HTTPHeader *string `json:"httpHeader,omitempty" tf:"http_header,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project. Changing this forces a new Service Connection Incoming WebHook to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The name of the service endpoint. Changing this forces a new Service Connection Incoming WebHook to be created.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The name of the WebHook.
	// The name of the WebHook.
	WebhookName *string `json:"webhookName,omitempty" tf:"webhook_name,omitempty"`
}

type IncomingwebhookParameters struct {

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Http header name on which checksum will be sent.
	// Optional http header name on which checksum will be sent.
	// +kubebuilder:validation:Optional
	HTTPHeader *string `json:"httpHeader,omitempty" tf:"http_header,omitempty"`

	// The ID of the project. Changing this forces a new Service Connection Incoming WebHook to be created.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Secret for the WebHook. WebHook service will use this secret to calculate the payload checksum.
	// Optional secret for the webhook. WebHook service will use this secret to calculate the payload checksum.
	// +kubebuilder:validation:Optional
	SecretSecretRef *v1.SecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// The name of the service endpoint. Changing this forces a new Service Connection Incoming WebHook to be created.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The name of the WebHook.
	// The name of the WebHook.
	// +kubebuilder:validation:Optional
	WebhookName *string `json:"webhookName,omitempty" tf:"webhook_name,omitempty"`
}

// IncomingwebhookSpec defines the desired state of Incomingwebhook
type IncomingwebhookSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IncomingwebhookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IncomingwebhookInitParameters `json:"initProvider,omitempty"`
}

// IncomingwebhookStatus defines the observed state of Incomingwebhook.
type IncomingwebhookStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IncomingwebhookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Incomingwebhook is the Schema for the Incomingwebhooks API. Manages a Service Connection Incoming WebHook.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type Incomingwebhook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.webhookName) || (has(self.initProvider) && has(self.initProvider.webhookName))",message="spec.forProvider.webhookName is a required parameter"
	Spec   IncomingwebhookSpec   `json:"spec"`
	Status IncomingwebhookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IncomingwebhookList contains a list of Incomingwebhooks
type IncomingwebhookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Incomingwebhook `json:"items"`
}

// Repository type metadata.
var (
	Incomingwebhook_Kind             = "Incomingwebhook"
	Incomingwebhook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Incomingwebhook_Kind}.String()
	Incomingwebhook_KindAPIVersion   = Incomingwebhook_Kind + "." + CRDGroupVersion.String()
	Incomingwebhook_GroupVersionKind = CRDGroupVersion.WithKind(Incomingwebhook_Kind)
)

func init() {
	SchemeBuilder.Register(&Incomingwebhook{}, &IncomingwebhookList{})
}
