// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type JenkinsInitParameters struct {

	// Allows the Jenkins clients to accept self-signed SSL server certificates. Defaults to false.
	// Allows the Jenkins clients to accept self-signed SSL server certificates without installing them into the TFS service role and/or Build Agent computers.
	AcceptUntrustedCerts *bool `json:"acceptUntrustedCerts,omitempty" tf:"accept_untrusted_certs,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The Service Endpoint password to authenticate at the Jenkins Instance.
	// The Jenkins password.
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The ID of the project. Changing this forces a new Service Connection Jenkins to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The name of the service endpoint. Changing this forces a new Service Connection Jenkins to be created.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The Service Endpoint url.
	// Url for the Jenkins Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The Service Endpoint username to authenticate at the Jenkins Instance.
	// The Jenkins user name.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type JenkinsObservation struct {

	// Allows the Jenkins clients to accept self-signed SSL server certificates. Defaults to false.
	// Allows the Jenkins clients to accept self-signed SSL server certificates without installing them into the TFS service role and/or Build Agent computers.
	AcceptUntrustedCerts *bool `json:"acceptUntrustedCerts,omitempty" tf:"accept_untrusted_certs,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project. Changing this forces a new Service Connection Jenkins to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The name of the service endpoint. Changing this forces a new Service Connection Jenkins to be created.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The Service Endpoint url.
	// Url for the Jenkins Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The Service Endpoint username to authenticate at the Jenkins Instance.
	// The Jenkins user name.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type JenkinsParameters struct {

	// Allows the Jenkins clients to accept self-signed SSL server certificates. Defaults to false.
	// Allows the Jenkins clients to accept self-signed SSL server certificates without installing them into the TFS service role and/or Build Agent computers.
	// +kubebuilder:validation:Optional
	AcceptUntrustedCerts *bool `json:"acceptUntrustedCerts,omitempty" tf:"accept_untrusted_certs,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The Service Endpoint password to authenticate at the Jenkins Instance.
	// The Jenkins password.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The ID of the project. Changing this forces a new Service Connection Jenkins to be created.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The name of the service endpoint. Changing this forces a new Service Connection Jenkins to be created.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The Service Endpoint url.
	// Url for the Jenkins Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The Service Endpoint username to authenticate at the Jenkins Instance.
	// The Jenkins user name.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// JenkinsSpec defines the desired state of Jenkins
type JenkinsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     JenkinsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider JenkinsInitParameters `json:"initProvider,omitempty"`
}

// JenkinsStatus defines the observed state of Jenkins.
type JenkinsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        JenkinsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Jenkins is the Schema for the Jenkinss API. Manages a Service Connection for Jenkins.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type Jenkins struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   JenkinsSpec   `json:"spec"`
	Status JenkinsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// JenkinsList contains a list of Jenkinss
type JenkinsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Jenkins `json:"items"`
}

// Repository type metadata.
var (
	Jenkins_Kind             = "Jenkins"
	Jenkins_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Jenkins_Kind}.String()
	Jenkins_KindAPIVersion   = Jenkins_Kind + "." + CRDGroupVersion.String()
	Jenkins_GroupVersionKind = CRDGroupVersion.WithKind(Jenkins_Kind)
)

func init() {
	SchemeBuilder.Register(&Jenkins{}, &JenkinsList{})
}
