// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AzureSubscriptionInitParameters struct {

	// Azure environment refers to whether the public cloud offering or domestic (government) clouds are being used. Currently, only the public cloud is supported. The value must be AzureCloud. This is also the default-value.
	// type of azure cloud: AzureCloud
	AzureEnvironment *string `json:"azureEnvironment,omitempty" tf:"azure_environment,omitempty"`

	// Set this option to allow use cluster admin credentials.
	// Enable Cluster Admin
	ClusterAdmin *bool `json:"clusterAdmin,omitempty" tf:"cluster_admin,omitempty"`

	// The name of the Kubernetes cluster.
	// name of aks-resource
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// The Kubernetes namespace. Default value is "default".
	// accessed namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The resource group name, to which the Kubernetes cluster is deployed.
	// id of resourcegroup
	ResourcegroupID *string `json:"resourcegroupId,omitempty" tf:"resourcegroup_id,omitempty"`

	// The id of the Azure subscription.
	// id of azure subscription
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`

	// The name of the Azure subscription.
	// name of azure subscription
	SubscriptionName *string `json:"subscriptionName,omitempty" tf:"subscription_name,omitempty"`

	// The id of the tenant used by the subscription.
	// id of aad-tenant
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type AzureSubscriptionObservation struct {

	// Azure environment refers to whether the public cloud offering or domestic (government) clouds are being used. Currently, only the public cloud is supported. The value must be AzureCloud. This is also the default-value.
	// type of azure cloud: AzureCloud
	AzureEnvironment *string `json:"azureEnvironment,omitempty" tf:"azure_environment,omitempty"`

	// Set this option to allow use cluster admin credentials.
	// Enable Cluster Admin
	ClusterAdmin *bool `json:"clusterAdmin,omitempty" tf:"cluster_admin,omitempty"`

	// The name of the Kubernetes cluster.
	// name of aks-resource
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// The Kubernetes namespace. Default value is "default".
	// accessed namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The resource group name, to which the Kubernetes cluster is deployed.
	// id of resourcegroup
	ResourcegroupID *string `json:"resourcegroupId,omitempty" tf:"resourcegroup_id,omitempty"`

	// The id of the Azure subscription.
	// id of azure subscription
	SubscriptionID *string `json:"subscriptionId,omitempty" tf:"subscription_id,omitempty"`

	// The name of the Azure subscription.
	// name of azure subscription
	SubscriptionName *string `json:"subscriptionName,omitempty" tf:"subscription_name,omitempty"`

	// The id of the tenant used by the subscription.
	// id of aad-tenant
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type AzureSubscriptionParameters struct {

	// Azure environment refers to whether the public cloud offering or domestic (government) clouds are being used. Currently, only the public cloud is supported. The value must be AzureCloud. This is also the default-value.
	// type of azure cloud: AzureCloud
	// +kubebuilder:validation:Optional
	AzureEnvironment *string `json:"azureEnvironment,omitempty" tf:"azure_environment,omitempty"`

	// Set this option to allow use cluster admin credentials.
	// Enable Cluster Admin
	// +kubebuilder:validation:Optional
	ClusterAdmin *bool `json:"clusterAdmin,omitempty" tf:"cluster_admin,omitempty"`

	// The name of the Kubernetes cluster.
	// name of aks-resource
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName" tf:"cluster_name,omitempty"`

	// The Kubernetes namespace. Default value is "default".
	// accessed namespace
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The resource group name, to which the Kubernetes cluster is deployed.
	// id of resourcegroup
	// +kubebuilder:validation:Optional
	ResourcegroupID *string `json:"resourcegroupId" tf:"resourcegroup_id,omitempty"`

	// The id of the Azure subscription.
	// id of azure subscription
	// +kubebuilder:validation:Optional
	SubscriptionID *string `json:"subscriptionId" tf:"subscription_id,omitempty"`

	// The name of the Azure subscription.
	// name of azure subscription
	// +kubebuilder:validation:Optional
	SubscriptionName *string `json:"subscriptionName" tf:"subscription_name,omitempty"`

	// The id of the tenant used by the subscription.
	// id of aad-tenant
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId" tf:"tenant_id,omitempty"`
}

type KubeconfigInitParameters struct {

	// Set this option to allow clients to accept a self-signed certificate.
	// Enable this if your authentication uses untrusted certificates
	AcceptUntrustedCerts *bool `json:"acceptUntrustedCerts,omitempty" tf:"accept_untrusted_certs,omitempty"`

	// Context within the kubeconfig file that is to be used for identifying the cluster. Default value is the current-context set in kubeconfig.
	// Context of your cluster
	ClusterContext *string `json:"clusterContext,omitempty" tf:"cluster_context,omitempty"`

	// The content of the kubeconfig in yaml notation to be used to communicate with the API-Server of Kubernetes.
	// Content of the kubeconfig file. The configuration information in your kubeconfig file allows Kubernetes clients to talk to your Kubernetes API servers. This file is used by kubectl and all supported Kubernetes clients.
	KubeConfigSecretRef v1.SecretKeySelector `json:"kubeConfigSecretRef" tf:"-"`
}

type KubeconfigObservation struct {

	// Set this option to allow clients to accept a self-signed certificate.
	// Enable this if your authentication uses untrusted certificates
	AcceptUntrustedCerts *bool `json:"acceptUntrustedCerts,omitempty" tf:"accept_untrusted_certs,omitempty"`

	// Context within the kubeconfig file that is to be used for identifying the cluster. Default value is the current-context set in kubeconfig.
	// Context of your cluster
	ClusterContext *string `json:"clusterContext,omitempty" tf:"cluster_context,omitempty"`
}

type KubeconfigParameters struct {

	// Set this option to allow clients to accept a self-signed certificate.
	// Enable this if your authentication uses untrusted certificates
	// +kubebuilder:validation:Optional
	AcceptUntrustedCerts *bool `json:"acceptUntrustedCerts,omitempty" tf:"accept_untrusted_certs,omitempty"`

	// Context within the kubeconfig file that is to be used for identifying the cluster. Default value is the current-context set in kubeconfig.
	// Context of your cluster
	// +kubebuilder:validation:Optional
	ClusterContext *string `json:"clusterContext,omitempty" tf:"cluster_context,omitempty"`

	// The content of the kubeconfig in yaml notation to be used to communicate with the API-Server of Kubernetes.
	// Content of the kubeconfig file. The configuration information in your kubeconfig file allows Kubernetes clients to talk to your Kubernetes API servers. This file is used by kubectl and all supported Kubernetes clients.
	// +kubebuilder:validation:Optional
	KubeConfigSecretRef v1.SecretKeySelector `json:"kubeConfigSecretRef" tf:"-"`
}

type KubernetesInitParameters struct {

	// The hostname (in form of URI) of the Kubernetes API.
	// URL to Kubernete's API-Server
	ApiserverURL *string `json:"apiserverUrl,omitempty" tf:"apiserver_url,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The authentication method used to authenticate on the Kubernetes cluster. The value should be one of AzureSubscription, Kubeconfig, ServiceAccount.
	// Type of credentials to use
	AuthorizationType *string `json:"authorizationType,omitempty" tf:"authorization_type,omitempty"`

	// A azure_subscription block defined blow.
	// 'AzureSubscription'-type of configuration
	AzureSubscription []AzureSubscriptionInitParameters `json:"azureSubscription,omitempty" tf:"azure_subscription,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A kubeconfig block defined blow.
	// 'Kubeconfig'-type of configuration
	Kubeconfig []KubeconfigInitParameters `json:"kubeconfig,omitempty" tf:"kubeconfig,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// A service_account block defined blow.
	// 'ServiceAccount'-type of configuration
	ServiceAccount []ServiceAccountInitParameters `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

type KubernetesObservation struct {

	// The hostname (in form of URI) of the Kubernetes API.
	// URL to Kubernete's API-Server
	ApiserverURL *string `json:"apiserverUrl,omitempty" tf:"apiserver_url,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The authentication method used to authenticate on the Kubernetes cluster. The value should be one of AzureSubscription, Kubeconfig, ServiceAccount.
	// Type of credentials to use
	AuthorizationType *string `json:"authorizationType,omitempty" tf:"authorization_type,omitempty"`

	// A azure_subscription block defined blow.
	// 'AzureSubscription'-type of configuration
	AzureSubscription []AzureSubscriptionObservation `json:"azureSubscription,omitempty" tf:"azure_subscription,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A kubeconfig block defined blow.
	// 'Kubeconfig'-type of configuration
	Kubeconfig []KubeconfigObservation `json:"kubeconfig,omitempty" tf:"kubeconfig,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// A service_account block defined blow.
	// 'ServiceAccount'-type of configuration
	ServiceAccount []ServiceAccountParameters `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

type KubernetesParameters struct {

	// The hostname (in form of URI) of the Kubernetes API.
	// URL to Kubernete's API-Server
	// +kubebuilder:validation:Optional
	ApiserverURL *string `json:"apiserverUrl,omitempty" tf:"apiserver_url,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The authentication method used to authenticate on the Kubernetes cluster. The value should be one of AzureSubscription, Kubeconfig, ServiceAccount.
	// Type of credentials to use
	// +kubebuilder:validation:Optional
	AuthorizationType *string `json:"authorizationType,omitempty" tf:"authorization_type,omitempty"`

	// A azure_subscription block defined blow.
	// 'AzureSubscription'-type of configuration
	// +kubebuilder:validation:Optional
	AzureSubscription []AzureSubscriptionParameters `json:"azureSubscription,omitempty" tf:"azure_subscription,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A kubeconfig block defined blow.
	// 'Kubeconfig'-type of configuration
	// +kubebuilder:validation:Optional
	Kubeconfig []KubeconfigParameters `json:"kubeconfig,omitempty" tf:"kubeconfig,omitempty"`

	// The ID of the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// A service_account block defined blow.
	// 'ServiceAccount'-type of configuration
	// +kubebuilder:validation:Optional
	ServiceAccount []ServiceAccountParameters `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// The Service Endpoint name.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`
}

type ServiceAccountInitParameters struct {

	// The certificate from a Kubernetes secret object.
	// Secret cert
	CACertSecretRef v1.SecretKeySelector `json:"caCertSecretRef" tf:"-"`

	// The token from a Kubernetes secret object.
	// Secret token
	TokenSecretRef v1.SecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type ServiceAccountObservation struct {
}

type ServiceAccountParameters struct {

	// The certificate from a Kubernetes secret object.
	// Secret cert
	// +kubebuilder:validation:Optional
	CACertSecretRef v1.SecretKeySelector `json:"caCertSecretRef" tf:"-"`

	// The token from a Kubernetes secret object.
	// Secret token
	// +kubebuilder:validation:Optional
	TokenSecretRef v1.SecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

// KubernetesSpec defines the desired state of Kubernetes
type KubernetesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KubernetesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KubernetesInitParameters `json:"initProvider,omitempty"`
}

// KubernetesStatus defines the observed state of Kubernetes.
type KubernetesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KubernetesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Kubernetes is the Schema for the Kubernetess API. Manages a Kubernetes service endpoint Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type Kubernetes struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiserverUrl) || (has(self.initProvider) && has(self.initProvider.apiserverUrl))",message="spec.forProvider.apiserverUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authorizationType) || (has(self.initProvider) && has(self.initProvider.authorizationType))",message="spec.forProvider.authorizationType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	Spec   KubernetesSpec   `json:"spec"`
	Status KubernetesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KubernetesList contains a list of Kubernetess
type KubernetesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Kubernetes `json:"items"`
}

// Repository type metadata.
var (
	Kubernetes_Kind             = "Kubernetes"
	Kubernetes_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Kubernetes_Kind}.String()
	Kubernetes_KindAPIVersion   = Kubernetes_Kind + "." + CRDGroupVersion.String()
	Kubernetes_GroupVersionKind = CRDGroupVersion.WithKind(Kubernetes_Kind)
)

func init() {
	SchemeBuilder.Register(&Kubernetes{}, &KubernetesList{})
}
